# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class GraphThreatNodeInfo(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "cloud_compliance_count",
            "node_type",
            "nodes",
            "secrets_count",
            "count",
            "id",
            "label",
            "vulnerability_count",
            "attack_path",
            "compliance_count",
        }
        
        class properties:
            
            
            class attack_path(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    
                    class items(
                        schemas.ListSchema
                    ):
                    
                    
                        class MetaOapg:
                            items = schemas.StrSchema
                    
                        def __new__(
                            cls,
                            _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                        ) -> 'items':
                            return super().__new__(
                                cls,
                                _arg,
                                _configuration=_configuration,
                            )
                    
                        def __getitem__(self, i: int) -> MetaOapg.items:
                            return super().__getitem__(i)
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'attack_path':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            cloud_compliance_count = schemas.IntSchema
            compliance_count = schemas.IntSchema
            count = schemas.IntSchema
            id = schemas.StrSchema
            label = schemas.StrSchema
            node_type = schemas.StrSchema
            
            
            class nodes(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def additional_properties() -> typing.Type['GraphNodeInfo']:
                        return GraphNodeInfo
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> 'GraphNodeInfo':
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> 'GraphNodeInfo':
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: 'GraphNodeInfo',
                ) -> 'nodes':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            secrets_count = schemas.IntSchema
            vulnerability_count = schemas.IntSchema
            __annotations__ = {
                "attack_path": attack_path,
                "cloud_compliance_count": cloud_compliance_count,
                "compliance_count": compliance_count,
                "count": count,
                "id": id,
                "label": label,
                "node_type": node_type,
                "nodes": nodes,
                "secrets_count": secrets_count,
                "vulnerability_count": vulnerability_count,
            }
    
    cloud_compliance_count: MetaOapg.properties.cloud_compliance_count
    node_type: MetaOapg.properties.node_type
    nodes: MetaOapg.properties.nodes
    secrets_count: MetaOapg.properties.secrets_count
    count: MetaOapg.properties.count
    id: MetaOapg.properties.id
    label: MetaOapg.properties.label
    vulnerability_count: MetaOapg.properties.vulnerability_count
    attack_path: MetaOapg.properties.attack_path
    compliance_count: MetaOapg.properties.compliance_count
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attack_path"]) -> MetaOapg.properties.attack_path: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cloud_compliance_count"]) -> MetaOapg.properties.cloud_compliance_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["compliance_count"]) -> MetaOapg.properties.compliance_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["count"]) -> MetaOapg.properties.count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["label"]) -> MetaOapg.properties.label: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_type"]) -> MetaOapg.properties.node_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nodes"]) -> MetaOapg.properties.nodes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["secrets_count"]) -> MetaOapg.properties.secrets_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vulnerability_count"]) -> MetaOapg.properties.vulnerability_count: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["attack_path", "cloud_compliance_count", "compliance_count", "count", "id", "label", "node_type", "nodes", "secrets_count", "vulnerability_count", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attack_path"]) -> MetaOapg.properties.attack_path: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cloud_compliance_count"]) -> MetaOapg.properties.cloud_compliance_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["compliance_count"]) -> MetaOapg.properties.compliance_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["count"]) -> MetaOapg.properties.count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["label"]) -> MetaOapg.properties.label: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_type"]) -> MetaOapg.properties.node_type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nodes"]) -> MetaOapg.properties.nodes: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["secrets_count"]) -> MetaOapg.properties.secrets_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vulnerability_count"]) -> MetaOapg.properties.vulnerability_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["attack_path", "cloud_compliance_count", "compliance_count", "count", "id", "label", "node_type", "nodes", "secrets_count", "vulnerability_count", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        cloud_compliance_count: typing.Union[MetaOapg.properties.cloud_compliance_count, decimal.Decimal, int, ],
        node_type: typing.Union[MetaOapg.properties.node_type, str, ],
        nodes: typing.Union[MetaOapg.properties.nodes, dict, frozendict.frozendict, None, ],
        secrets_count: typing.Union[MetaOapg.properties.secrets_count, decimal.Decimal, int, ],
        count: typing.Union[MetaOapg.properties.count, decimal.Decimal, int, ],
        id: typing.Union[MetaOapg.properties.id, str, ],
        label: typing.Union[MetaOapg.properties.label, str, ],
        vulnerability_count: typing.Union[MetaOapg.properties.vulnerability_count, decimal.Decimal, int, ],
        attack_path: typing.Union[MetaOapg.properties.attack_path, list, tuple, None, ],
        compliance_count: typing.Union[MetaOapg.properties.compliance_count, decimal.Decimal, int, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'GraphThreatNodeInfo':
        return super().__new__(
            cls,
            *_args,
            cloud_compliance_count=cloud_compliance_count,
            node_type=node_type,
            nodes=nodes,
            secrets_count=secrets_count,
            count=count,
            id=id,
            label=label,
            vulnerability_count=vulnerability_count,
            attack_path=attack_path,
            compliance_count=compliance_count,
            _configuration=_configuration,
            **kwargs,
        )

from threatmapper.model.graph_node_info import GraphNodeInfo
