# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class GraphTopologyFilters(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "host_filter",
            "field_filters",
            "container_filter",
            "cloud_filter",
            "kubernetes_filter",
            "pod_filter",
            "region_filter",
        }
        
        class properties:
            
            
            class cloud_filter(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'cloud_filter':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class container_filter(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'container_filter':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def field_filters() -> typing.Type['ReportersFieldsFilters']:
                return ReportersFieldsFilters
            
            
            class host_filter(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'host_filter':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class kubernetes_filter(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'kubernetes_filter':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class pod_filter(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'pod_filter':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class region_filter(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'region_filter':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "cloud_filter": cloud_filter,
                "container_filter": container_filter,
                "field_filters": field_filters,
                "host_filter": host_filter,
                "kubernetes_filter": kubernetes_filter,
                "pod_filter": pod_filter,
                "region_filter": region_filter,
            }
    
    host_filter: MetaOapg.properties.host_filter
    field_filters: 'ReportersFieldsFilters'
    container_filter: MetaOapg.properties.container_filter
    cloud_filter: MetaOapg.properties.cloud_filter
    kubernetes_filter: MetaOapg.properties.kubernetes_filter
    pod_filter: MetaOapg.properties.pod_filter
    region_filter: MetaOapg.properties.region_filter
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cloud_filter"]) -> MetaOapg.properties.cloud_filter: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["container_filter"]) -> MetaOapg.properties.container_filter: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["field_filters"]) -> 'ReportersFieldsFilters': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["host_filter"]) -> MetaOapg.properties.host_filter: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_filter"]) -> MetaOapg.properties.kubernetes_filter: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pod_filter"]) -> MetaOapg.properties.pod_filter: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["region_filter"]) -> MetaOapg.properties.region_filter: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cloud_filter", "container_filter", "field_filters", "host_filter", "kubernetes_filter", "pod_filter", "region_filter", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cloud_filter"]) -> MetaOapg.properties.cloud_filter: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["container_filter"]) -> MetaOapg.properties.container_filter: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["field_filters"]) -> 'ReportersFieldsFilters': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["host_filter"]) -> MetaOapg.properties.host_filter: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_filter"]) -> MetaOapg.properties.kubernetes_filter: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pod_filter"]) -> MetaOapg.properties.pod_filter: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["region_filter"]) -> MetaOapg.properties.region_filter: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cloud_filter", "container_filter", "field_filters", "host_filter", "kubernetes_filter", "pod_filter", "region_filter", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        host_filter: typing.Union[MetaOapg.properties.host_filter, list, tuple, None, ],
        field_filters: 'ReportersFieldsFilters',
        container_filter: typing.Union[MetaOapg.properties.container_filter, list, tuple, None, ],
        cloud_filter: typing.Union[MetaOapg.properties.cloud_filter, list, tuple, None, ],
        kubernetes_filter: typing.Union[MetaOapg.properties.kubernetes_filter, list, tuple, None, ],
        pod_filter: typing.Union[MetaOapg.properties.pod_filter, list, tuple, None, ],
        region_filter: typing.Union[MetaOapg.properties.region_filter, list, tuple, None, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'GraphTopologyFilters':
        return super().__new__(
            cls,
            *_args,
            host_filter=host_filter,
            field_filters=field_filters,
            container_filter=container_filter,
            cloud_filter=cloud_filter,
            kubernetes_filter=kubernetes_filter,
            pod_filter=pod_filter,
            region_filter=region_filter,
            _configuration=_configuration,
            **kwargs,
        )

from threatmapper.model.reporters_fields_filters import ReportersFieldsFilters
