# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class IngestersCloudResource(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            access_level = schemas.StrSchema
            account_id = schemas.StrSchema
            action = schemas.StrSchema
            allow_blob_public_access = schemas.BoolSchema
            arn = schemas.StrSchema
            attached_policy_arns = schemas.AnyTypeSchema
            block_public_acls = schemas.BoolSchema
            block_public_policy = schemas.BoolSchema
            bucket_policy_is_public = schemas.BoolSchema
            cidr_ipv4 = schemas.StrSchema
            cloud_provider = schemas.StrSchema
            container_definitions = schemas.AnyTypeSchema
            containers = schemas.AnyTypeSchema
            create_date = schemas.StrSchema
            db_cluster_identifier = schemas.StrSchema
            description = schemas.StrSchema
            event_notification_configuration = schemas.AnyTypeSchema
            group_id = schemas.StrSchema
            groups = schemas.AnyTypeSchema
            host_name = schemas.StrSchema
            iam_instance_profile_arn = schemas.StrSchema
            iam_instance_profile_id = schemas.StrSchema
            iam_policy = schemas.AnyTypeSchema
            id = schemas.StrSchema
            ignore_public_acls = schemas.BoolSchema
            ingress_settings = schemas.StrSchema
            inline_policies = schemas.AnyTypeSchema
            instance_id = schemas.StrSchema
            instance_profile_arns = schemas.AnyTypeSchema
            instances = schemas.AnyTypeSchema
            ip_configuration = schemas.AnyTypeSchema
            is_egress = schemas.BoolSchema
            name = schemas.StrSchema
            network_configuration = schemas.AnyTypeSchema
            network_interfaces = schemas.AnyTypeSchema
            network_mode = schemas.StrSchema
            organization_id = schemas.StrSchema
            organization_master_account_arn = schemas.StrSchema
            organization_master_account_email = schemas.StrSchema
            path = schemas.StrSchema
            policy = schemas.AnyTypeSchema
            policy_std = schemas.AnyTypeSchema
            privilege = schemas.StrSchema
            public_access = schemas.StrSchema
            public_ip_address = schemas.StrSchema
            public_ips = schemas.AnyTypeSchema
            public_network_access = schemas.StrSchema
            region = schemas.StrSchema
            resource_id = schemas.StrSchema
            resource_vpc_config = schemas.AnyTypeSchema
            resources_vpc_config = schemas.AnyTypeSchema
            restrict_public_buckets = schemas.BoolSchema
            scheme = schemas.StrSchema
            security_groups = schemas.AnyTypeSchema
            service_name = schemas.StrSchema
            storage_account_name = schemas.StrSchema
            target_group_arn = schemas.StrSchema
            target_health_descriptions = schemas.AnyTypeSchema
            task_definition = schemas.AnyTypeSchema
            task_definition_arn = schemas.StrSchema
            user_groups = schemas.AnyTypeSchema
            user_id = schemas.StrSchema
            users = schemas.AnyTypeSchema
            vpc_id = schemas.StrSchema
            vpc_options = schemas.AnyTypeSchema
            vpc_security_group_ids = schemas.AnyTypeSchema
            vpc_security_groups = schemas.AnyTypeSchema
            __annotations__ = {
                "access_level": access_level,
                "account_id": account_id,
                "action": action,
                "allow_blob_public_access": allow_blob_public_access,
                "arn": arn,
                "attached_policy_arns": attached_policy_arns,
                "block_public_acls": block_public_acls,
                "block_public_policy": block_public_policy,
                "bucket_policy_is_public": bucket_policy_is_public,
                "cidr_ipv4": cidr_ipv4,
                "cloud_provider": cloud_provider,
                "container_definitions": container_definitions,
                "containers": containers,
                "create_date": create_date,
                "db_cluster_identifier": db_cluster_identifier,
                "description": description,
                "event_notification_configuration": event_notification_configuration,
                "group_id": group_id,
                "groups": groups,
                "host_name": host_name,
                "iam_instance_profile_arn": iam_instance_profile_arn,
                "iam_instance_profile_id": iam_instance_profile_id,
                "iam_policy": iam_policy,
                "id": id,
                "ignore_public_acls": ignore_public_acls,
                "ingress_settings": ingress_settings,
                "inline_policies": inline_policies,
                "instance_id": instance_id,
                "instance_profile_arns": instance_profile_arns,
                "instances": instances,
                "ip_configuration": ip_configuration,
                "is_egress": is_egress,
                "name": name,
                "network_configuration": network_configuration,
                "network_interfaces": network_interfaces,
                "network_mode": network_mode,
                "organization_id": organization_id,
                "organization_master_account_arn": organization_master_account_arn,
                "organization_master_account_email": organization_master_account_email,
                "path": path,
                "policy": policy,
                "policy_std": policy_std,
                "privilege": privilege,
                "public_access": public_access,
                "public_ip_address": public_ip_address,
                "public_ips": public_ips,
                "public_network_access": public_network_access,
                "region": region,
                "resource_id": resource_id,
                "resource_vpc_config": resource_vpc_config,
                "resources_vpc_config": resources_vpc_config,
                "restrict_public_buckets": restrict_public_buckets,
                "scheme": scheme,
                "security_groups": security_groups,
                "service_name": service_name,
                "storage_account_name": storage_account_name,
                "target_group_arn": target_group_arn,
                "target_health_descriptions": target_health_descriptions,
                "task_definition": task_definition,
                "task_definition_arn": task_definition_arn,
                "user-groups": user_groups,
                "user_id": user_id,
                "users": users,
                "vpc_id": vpc_id,
                "vpc_options": vpc_options,
                "vpc_security_group_ids": vpc_security_group_ids,
                "vpc_security_groups": vpc_security_groups,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["access_level"]) -> MetaOapg.properties.access_level: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["account_id"]) -> MetaOapg.properties.account_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["action"]) -> MetaOapg.properties.action: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["allow_blob_public_access"]) -> MetaOapg.properties.allow_blob_public_access: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["arn"]) -> MetaOapg.properties.arn: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attached_policy_arns"]) -> MetaOapg.properties.attached_policy_arns: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["block_public_acls"]) -> MetaOapg.properties.block_public_acls: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["block_public_policy"]) -> MetaOapg.properties.block_public_policy: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bucket_policy_is_public"]) -> MetaOapg.properties.bucket_policy_is_public: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cidr_ipv4"]) -> MetaOapg.properties.cidr_ipv4: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cloud_provider"]) -> MetaOapg.properties.cloud_provider: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["container_definitions"]) -> MetaOapg.properties.container_definitions: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["containers"]) -> MetaOapg.properties.containers: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["create_date"]) -> MetaOapg.properties.create_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["db_cluster_identifier"]) -> MetaOapg.properties.db_cluster_identifier: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["event_notification_configuration"]) -> MetaOapg.properties.event_notification_configuration: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["group_id"]) -> MetaOapg.properties.group_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["groups"]) -> MetaOapg.properties.groups: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["host_name"]) -> MetaOapg.properties.host_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["iam_instance_profile_arn"]) -> MetaOapg.properties.iam_instance_profile_arn: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["iam_instance_profile_id"]) -> MetaOapg.properties.iam_instance_profile_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["iam_policy"]) -> MetaOapg.properties.iam_policy: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ignore_public_acls"]) -> MetaOapg.properties.ignore_public_acls: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ingress_settings"]) -> MetaOapg.properties.ingress_settings: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["inline_policies"]) -> MetaOapg.properties.inline_policies: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["instance_id"]) -> MetaOapg.properties.instance_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["instance_profile_arns"]) -> MetaOapg.properties.instance_profile_arns: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["instances"]) -> MetaOapg.properties.instances: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ip_configuration"]) -> MetaOapg.properties.ip_configuration: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_egress"]) -> MetaOapg.properties.is_egress: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["network_configuration"]) -> MetaOapg.properties.network_configuration: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["network_interfaces"]) -> MetaOapg.properties.network_interfaces: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["network_mode"]) -> MetaOapg.properties.network_mode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["organization_id"]) -> MetaOapg.properties.organization_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["organization_master_account_arn"]) -> MetaOapg.properties.organization_master_account_arn: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["organization_master_account_email"]) -> MetaOapg.properties.organization_master_account_email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["path"]) -> MetaOapg.properties.path: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["policy"]) -> MetaOapg.properties.policy: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["policy_std"]) -> MetaOapg.properties.policy_std: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["privilege"]) -> MetaOapg.properties.privilege: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["public_access"]) -> MetaOapg.properties.public_access: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["public_ip_address"]) -> MetaOapg.properties.public_ip_address: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["public_ips"]) -> MetaOapg.properties.public_ips: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["public_network_access"]) -> MetaOapg.properties.public_network_access: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["region"]) -> MetaOapg.properties.region: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resource_id"]) -> MetaOapg.properties.resource_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resource_vpc_config"]) -> MetaOapg.properties.resource_vpc_config: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resources_vpc_config"]) -> MetaOapg.properties.resources_vpc_config: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["restrict_public_buckets"]) -> MetaOapg.properties.restrict_public_buckets: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scheme"]) -> MetaOapg.properties.scheme: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["security_groups"]) -> MetaOapg.properties.security_groups: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["service_name"]) -> MetaOapg.properties.service_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["storage_account_name"]) -> MetaOapg.properties.storage_account_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["target_group_arn"]) -> MetaOapg.properties.target_group_arn: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["target_health_descriptions"]) -> MetaOapg.properties.target_health_descriptions: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["task_definition"]) -> MetaOapg.properties.task_definition: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["task_definition_arn"]) -> MetaOapg.properties.task_definition_arn: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["user-groups"]) -> MetaOapg.properties.user_groups: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["user_id"]) -> MetaOapg.properties.user_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["users"]) -> MetaOapg.properties.users: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vpc_id"]) -> MetaOapg.properties.vpc_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vpc_options"]) -> MetaOapg.properties.vpc_options: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vpc_security_group_ids"]) -> MetaOapg.properties.vpc_security_group_ids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vpc_security_groups"]) -> MetaOapg.properties.vpc_security_groups: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["access_level", "account_id", "action", "allow_blob_public_access", "arn", "attached_policy_arns", "block_public_acls", "block_public_policy", "bucket_policy_is_public", "cidr_ipv4", "cloud_provider", "container_definitions", "containers", "create_date", "db_cluster_identifier", "description", "event_notification_configuration", "group_id", "groups", "host_name", "iam_instance_profile_arn", "iam_instance_profile_id", "iam_policy", "id", "ignore_public_acls", "ingress_settings", "inline_policies", "instance_id", "instance_profile_arns", "instances", "ip_configuration", "is_egress", "name", "network_configuration", "network_interfaces", "network_mode", "organization_id", "organization_master_account_arn", "organization_master_account_email", "path", "policy", "policy_std", "privilege", "public_access", "public_ip_address", "public_ips", "public_network_access", "region", "resource_id", "resource_vpc_config", "resources_vpc_config", "restrict_public_buckets", "scheme", "security_groups", "service_name", "storage_account_name", "target_group_arn", "target_health_descriptions", "task_definition", "task_definition_arn", "user-groups", "user_id", "users", "vpc_id", "vpc_options", "vpc_security_group_ids", "vpc_security_groups", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["access_level"]) -> typing.Union[MetaOapg.properties.access_level, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["account_id"]) -> typing.Union[MetaOapg.properties.account_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["action"]) -> typing.Union[MetaOapg.properties.action, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["allow_blob_public_access"]) -> typing.Union[MetaOapg.properties.allow_blob_public_access, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["arn"]) -> typing.Union[MetaOapg.properties.arn, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attached_policy_arns"]) -> typing.Union[MetaOapg.properties.attached_policy_arns, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["block_public_acls"]) -> typing.Union[MetaOapg.properties.block_public_acls, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["block_public_policy"]) -> typing.Union[MetaOapg.properties.block_public_policy, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bucket_policy_is_public"]) -> typing.Union[MetaOapg.properties.bucket_policy_is_public, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cidr_ipv4"]) -> typing.Union[MetaOapg.properties.cidr_ipv4, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cloud_provider"]) -> typing.Union[MetaOapg.properties.cloud_provider, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["container_definitions"]) -> typing.Union[MetaOapg.properties.container_definitions, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["containers"]) -> typing.Union[MetaOapg.properties.containers, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["create_date"]) -> typing.Union[MetaOapg.properties.create_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["db_cluster_identifier"]) -> typing.Union[MetaOapg.properties.db_cluster_identifier, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["event_notification_configuration"]) -> typing.Union[MetaOapg.properties.event_notification_configuration, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["group_id"]) -> typing.Union[MetaOapg.properties.group_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["groups"]) -> typing.Union[MetaOapg.properties.groups, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["host_name"]) -> typing.Union[MetaOapg.properties.host_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["iam_instance_profile_arn"]) -> typing.Union[MetaOapg.properties.iam_instance_profile_arn, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["iam_instance_profile_id"]) -> typing.Union[MetaOapg.properties.iam_instance_profile_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["iam_policy"]) -> typing.Union[MetaOapg.properties.iam_policy, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ignore_public_acls"]) -> typing.Union[MetaOapg.properties.ignore_public_acls, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ingress_settings"]) -> typing.Union[MetaOapg.properties.ingress_settings, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["inline_policies"]) -> typing.Union[MetaOapg.properties.inline_policies, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["instance_id"]) -> typing.Union[MetaOapg.properties.instance_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["instance_profile_arns"]) -> typing.Union[MetaOapg.properties.instance_profile_arns, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["instances"]) -> typing.Union[MetaOapg.properties.instances, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ip_configuration"]) -> typing.Union[MetaOapg.properties.ip_configuration, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_egress"]) -> typing.Union[MetaOapg.properties.is_egress, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["network_configuration"]) -> typing.Union[MetaOapg.properties.network_configuration, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["network_interfaces"]) -> typing.Union[MetaOapg.properties.network_interfaces, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["network_mode"]) -> typing.Union[MetaOapg.properties.network_mode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["organization_id"]) -> typing.Union[MetaOapg.properties.organization_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["organization_master_account_arn"]) -> typing.Union[MetaOapg.properties.organization_master_account_arn, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["organization_master_account_email"]) -> typing.Union[MetaOapg.properties.organization_master_account_email, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["path"]) -> typing.Union[MetaOapg.properties.path, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["policy"]) -> typing.Union[MetaOapg.properties.policy, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["policy_std"]) -> typing.Union[MetaOapg.properties.policy_std, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["privilege"]) -> typing.Union[MetaOapg.properties.privilege, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["public_access"]) -> typing.Union[MetaOapg.properties.public_access, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["public_ip_address"]) -> typing.Union[MetaOapg.properties.public_ip_address, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["public_ips"]) -> typing.Union[MetaOapg.properties.public_ips, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["public_network_access"]) -> typing.Union[MetaOapg.properties.public_network_access, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["region"]) -> typing.Union[MetaOapg.properties.region, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resource_id"]) -> typing.Union[MetaOapg.properties.resource_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resource_vpc_config"]) -> typing.Union[MetaOapg.properties.resource_vpc_config, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resources_vpc_config"]) -> typing.Union[MetaOapg.properties.resources_vpc_config, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["restrict_public_buckets"]) -> typing.Union[MetaOapg.properties.restrict_public_buckets, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scheme"]) -> typing.Union[MetaOapg.properties.scheme, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["security_groups"]) -> typing.Union[MetaOapg.properties.security_groups, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["service_name"]) -> typing.Union[MetaOapg.properties.service_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["storage_account_name"]) -> typing.Union[MetaOapg.properties.storage_account_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["target_group_arn"]) -> typing.Union[MetaOapg.properties.target_group_arn, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["target_health_descriptions"]) -> typing.Union[MetaOapg.properties.target_health_descriptions, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["task_definition"]) -> typing.Union[MetaOapg.properties.task_definition, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["task_definition_arn"]) -> typing.Union[MetaOapg.properties.task_definition_arn, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["user-groups"]) -> typing.Union[MetaOapg.properties.user_groups, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["user_id"]) -> typing.Union[MetaOapg.properties.user_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["users"]) -> typing.Union[MetaOapg.properties.users, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vpc_id"]) -> typing.Union[MetaOapg.properties.vpc_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vpc_options"]) -> typing.Union[MetaOapg.properties.vpc_options, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vpc_security_group_ids"]) -> typing.Union[MetaOapg.properties.vpc_security_group_ids, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vpc_security_groups"]) -> typing.Union[MetaOapg.properties.vpc_security_groups, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["access_level", "account_id", "action", "allow_blob_public_access", "arn", "attached_policy_arns", "block_public_acls", "block_public_policy", "bucket_policy_is_public", "cidr_ipv4", "cloud_provider", "container_definitions", "containers", "create_date", "db_cluster_identifier", "description", "event_notification_configuration", "group_id", "groups", "host_name", "iam_instance_profile_arn", "iam_instance_profile_id", "iam_policy", "id", "ignore_public_acls", "ingress_settings", "inline_policies", "instance_id", "instance_profile_arns", "instances", "ip_configuration", "is_egress", "name", "network_configuration", "network_interfaces", "network_mode", "organization_id", "organization_master_account_arn", "organization_master_account_email", "path", "policy", "policy_std", "privilege", "public_access", "public_ip_address", "public_ips", "public_network_access", "region", "resource_id", "resource_vpc_config", "resources_vpc_config", "restrict_public_buckets", "scheme", "security_groups", "service_name", "storage_account_name", "target_group_arn", "target_health_descriptions", "task_definition", "task_definition_arn", "user-groups", "user_id", "users", "vpc_id", "vpc_options", "vpc_security_group_ids", "vpc_security_groups", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        access_level: typing.Union[MetaOapg.properties.access_level, str, schemas.Unset] = schemas.unset,
        account_id: typing.Union[MetaOapg.properties.account_id, str, schemas.Unset] = schemas.unset,
        action: typing.Union[MetaOapg.properties.action, str, schemas.Unset] = schemas.unset,
        allow_blob_public_access: typing.Union[MetaOapg.properties.allow_blob_public_access, bool, schemas.Unset] = schemas.unset,
        arn: typing.Union[MetaOapg.properties.arn, str, schemas.Unset] = schemas.unset,
        attached_policy_arns: typing.Union[MetaOapg.properties.attached_policy_arns, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        block_public_acls: typing.Union[MetaOapg.properties.block_public_acls, bool, schemas.Unset] = schemas.unset,
        block_public_policy: typing.Union[MetaOapg.properties.block_public_policy, bool, schemas.Unset] = schemas.unset,
        bucket_policy_is_public: typing.Union[MetaOapg.properties.bucket_policy_is_public, bool, schemas.Unset] = schemas.unset,
        cidr_ipv4: typing.Union[MetaOapg.properties.cidr_ipv4, str, schemas.Unset] = schemas.unset,
        cloud_provider: typing.Union[MetaOapg.properties.cloud_provider, str, schemas.Unset] = schemas.unset,
        container_definitions: typing.Union[MetaOapg.properties.container_definitions, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        containers: typing.Union[MetaOapg.properties.containers, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        create_date: typing.Union[MetaOapg.properties.create_date, str, schemas.Unset] = schemas.unset,
        db_cluster_identifier: typing.Union[MetaOapg.properties.db_cluster_identifier, str, schemas.Unset] = schemas.unset,
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        event_notification_configuration: typing.Union[MetaOapg.properties.event_notification_configuration, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        group_id: typing.Union[MetaOapg.properties.group_id, str, schemas.Unset] = schemas.unset,
        groups: typing.Union[MetaOapg.properties.groups, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        host_name: typing.Union[MetaOapg.properties.host_name, str, schemas.Unset] = schemas.unset,
        iam_instance_profile_arn: typing.Union[MetaOapg.properties.iam_instance_profile_arn, str, schemas.Unset] = schemas.unset,
        iam_instance_profile_id: typing.Union[MetaOapg.properties.iam_instance_profile_id, str, schemas.Unset] = schemas.unset,
        iam_policy: typing.Union[MetaOapg.properties.iam_policy, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        ignore_public_acls: typing.Union[MetaOapg.properties.ignore_public_acls, bool, schemas.Unset] = schemas.unset,
        ingress_settings: typing.Union[MetaOapg.properties.ingress_settings, str, schemas.Unset] = schemas.unset,
        inline_policies: typing.Union[MetaOapg.properties.inline_policies, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        instance_id: typing.Union[MetaOapg.properties.instance_id, str, schemas.Unset] = schemas.unset,
        instance_profile_arns: typing.Union[MetaOapg.properties.instance_profile_arns, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        instances: typing.Union[MetaOapg.properties.instances, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        ip_configuration: typing.Union[MetaOapg.properties.ip_configuration, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        is_egress: typing.Union[MetaOapg.properties.is_egress, bool, schemas.Unset] = schemas.unset,
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        network_configuration: typing.Union[MetaOapg.properties.network_configuration, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        network_interfaces: typing.Union[MetaOapg.properties.network_interfaces, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        network_mode: typing.Union[MetaOapg.properties.network_mode, str, schemas.Unset] = schemas.unset,
        organization_id: typing.Union[MetaOapg.properties.organization_id, str, schemas.Unset] = schemas.unset,
        organization_master_account_arn: typing.Union[MetaOapg.properties.organization_master_account_arn, str, schemas.Unset] = schemas.unset,
        organization_master_account_email: typing.Union[MetaOapg.properties.organization_master_account_email, str, schemas.Unset] = schemas.unset,
        path: typing.Union[MetaOapg.properties.path, str, schemas.Unset] = schemas.unset,
        policy: typing.Union[MetaOapg.properties.policy, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        policy_std: typing.Union[MetaOapg.properties.policy_std, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        privilege: typing.Union[MetaOapg.properties.privilege, str, schemas.Unset] = schemas.unset,
        public_access: typing.Union[MetaOapg.properties.public_access, str, schemas.Unset] = schemas.unset,
        public_ip_address: typing.Union[MetaOapg.properties.public_ip_address, str, schemas.Unset] = schemas.unset,
        public_ips: typing.Union[MetaOapg.properties.public_ips, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        public_network_access: typing.Union[MetaOapg.properties.public_network_access, str, schemas.Unset] = schemas.unset,
        region: typing.Union[MetaOapg.properties.region, str, schemas.Unset] = schemas.unset,
        resource_id: typing.Union[MetaOapg.properties.resource_id, str, schemas.Unset] = schemas.unset,
        resource_vpc_config: typing.Union[MetaOapg.properties.resource_vpc_config, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        resources_vpc_config: typing.Union[MetaOapg.properties.resources_vpc_config, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        restrict_public_buckets: typing.Union[MetaOapg.properties.restrict_public_buckets, bool, schemas.Unset] = schemas.unset,
        scheme: typing.Union[MetaOapg.properties.scheme, str, schemas.Unset] = schemas.unset,
        security_groups: typing.Union[MetaOapg.properties.security_groups, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        service_name: typing.Union[MetaOapg.properties.service_name, str, schemas.Unset] = schemas.unset,
        storage_account_name: typing.Union[MetaOapg.properties.storage_account_name, str, schemas.Unset] = schemas.unset,
        target_group_arn: typing.Union[MetaOapg.properties.target_group_arn, str, schemas.Unset] = schemas.unset,
        target_health_descriptions: typing.Union[MetaOapg.properties.target_health_descriptions, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        task_definition: typing.Union[MetaOapg.properties.task_definition, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        task_definition_arn: typing.Union[MetaOapg.properties.task_definition_arn, str, schemas.Unset] = schemas.unset,
        user_id: typing.Union[MetaOapg.properties.user_id, str, schemas.Unset] = schemas.unset,
        users: typing.Union[MetaOapg.properties.users, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        vpc_id: typing.Union[MetaOapg.properties.vpc_id, str, schemas.Unset] = schemas.unset,
        vpc_options: typing.Union[MetaOapg.properties.vpc_options, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        vpc_security_group_ids: typing.Union[MetaOapg.properties.vpc_security_group_ids, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        vpc_security_groups: typing.Union[MetaOapg.properties.vpc_security_groups, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'IngestersCloudResource':
        return super().__new__(
            cls,
            *_args,
            access_level=access_level,
            account_id=account_id,
            action=action,
            allow_blob_public_access=allow_blob_public_access,
            arn=arn,
            attached_policy_arns=attached_policy_arns,
            block_public_acls=block_public_acls,
            block_public_policy=block_public_policy,
            bucket_policy_is_public=bucket_policy_is_public,
            cidr_ipv4=cidr_ipv4,
            cloud_provider=cloud_provider,
            container_definitions=container_definitions,
            containers=containers,
            create_date=create_date,
            db_cluster_identifier=db_cluster_identifier,
            description=description,
            event_notification_configuration=event_notification_configuration,
            group_id=group_id,
            groups=groups,
            host_name=host_name,
            iam_instance_profile_arn=iam_instance_profile_arn,
            iam_instance_profile_id=iam_instance_profile_id,
            iam_policy=iam_policy,
            id=id,
            ignore_public_acls=ignore_public_acls,
            ingress_settings=ingress_settings,
            inline_policies=inline_policies,
            instance_id=instance_id,
            instance_profile_arns=instance_profile_arns,
            instances=instances,
            ip_configuration=ip_configuration,
            is_egress=is_egress,
            name=name,
            network_configuration=network_configuration,
            network_interfaces=network_interfaces,
            network_mode=network_mode,
            organization_id=organization_id,
            organization_master_account_arn=organization_master_account_arn,
            organization_master_account_email=organization_master_account_email,
            path=path,
            policy=policy,
            policy_std=policy_std,
            privilege=privilege,
            public_access=public_access,
            public_ip_address=public_ip_address,
            public_ips=public_ips,
            public_network_access=public_network_access,
            region=region,
            resource_id=resource_id,
            resource_vpc_config=resource_vpc_config,
            resources_vpc_config=resources_vpc_config,
            restrict_public_buckets=restrict_public_buckets,
            scheme=scheme,
            security_groups=security_groups,
            service_name=service_name,
            storage_account_name=storage_account_name,
            target_group_arn=target_group_arn,
            target_health_descriptions=target_health_descriptions,
            task_definition=task_definition,
            task_definition_arn=task_definition_arn,
            user_id=user_id,
            users=users,
            vpc_id=vpc_id,
            vpc_options=vpc_options,
            vpc_security_group_ids=vpc_security_group_ids,
            vpc_security_groups=vpc_security_groups,
            _configuration=_configuration,
            **kwargs,
        )
