# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class IngestersCompliance(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            timestamp = schemas.StrSchema
            compliance_check_type = schemas.StrSchema
            description = schemas.StrSchema
            masked = schemas.BoolSchema
            node_id = schemas.StrSchema
            node_type = schemas.StrSchema
            remediation_ansible = schemas.StrSchema
            remediation_puppet = schemas.StrSchema
            remediation_script = schemas.StrSchema
            resource = schemas.StrSchema
            scan_id = schemas.StrSchema
            status = schemas.StrSchema
            test_category = schemas.StrSchema
            test_desc = schemas.StrSchema
            test_number = schemas.StrSchema
            test_rationale = schemas.StrSchema
            test_severity = schemas.StrSchema
            type = schemas.StrSchema
            __annotations__ = {
                "@timestamp": timestamp,
                "compliance_check_type": compliance_check_type,
                "description": description,
                "masked": masked,
                "node_id": node_id,
                "node_type": node_type,
                "remediation_ansible": remediation_ansible,
                "remediation_puppet": remediation_puppet,
                "remediation_script": remediation_script,
                "resource": resource,
                "scan_id": scan_id,
                "status": status,
                "test_category": test_category,
                "test_desc": test_desc,
                "test_number": test_number,
                "test_rationale": test_rationale,
                "test_severity": test_severity,
                "type": type,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["@timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["compliance_check_type"]) -> MetaOapg.properties.compliance_check_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["masked"]) -> MetaOapg.properties.masked: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_id"]) -> MetaOapg.properties.node_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_type"]) -> MetaOapg.properties.node_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["remediation_ansible"]) -> MetaOapg.properties.remediation_ansible: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["remediation_puppet"]) -> MetaOapg.properties.remediation_puppet: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["remediation_script"]) -> MetaOapg.properties.remediation_script: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resource"]) -> MetaOapg.properties.resource: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scan_id"]) -> MetaOapg.properties.scan_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["test_category"]) -> MetaOapg.properties.test_category: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["test_desc"]) -> MetaOapg.properties.test_desc: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["test_number"]) -> MetaOapg.properties.test_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["test_rationale"]) -> MetaOapg.properties.test_rationale: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["test_severity"]) -> MetaOapg.properties.test_severity: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["@timestamp", "compliance_check_type", "description", "masked", "node_id", "node_type", "remediation_ansible", "remediation_puppet", "remediation_script", "resource", "scan_id", "status", "test_category", "test_desc", "test_number", "test_rationale", "test_severity", "type", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["@timestamp"]) -> typing.Union[MetaOapg.properties.timestamp, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["compliance_check_type"]) -> typing.Union[MetaOapg.properties.compliance_check_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["masked"]) -> typing.Union[MetaOapg.properties.masked, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_id"]) -> typing.Union[MetaOapg.properties.node_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_type"]) -> typing.Union[MetaOapg.properties.node_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["remediation_ansible"]) -> typing.Union[MetaOapg.properties.remediation_ansible, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["remediation_puppet"]) -> typing.Union[MetaOapg.properties.remediation_puppet, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["remediation_script"]) -> typing.Union[MetaOapg.properties.remediation_script, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resource"]) -> typing.Union[MetaOapg.properties.resource, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scan_id"]) -> typing.Union[MetaOapg.properties.scan_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["test_category"]) -> typing.Union[MetaOapg.properties.test_category, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["test_desc"]) -> typing.Union[MetaOapg.properties.test_desc, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["test_number"]) -> typing.Union[MetaOapg.properties.test_number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["test_rationale"]) -> typing.Union[MetaOapg.properties.test_rationale, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["test_severity"]) -> typing.Union[MetaOapg.properties.test_severity, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["@timestamp", "compliance_check_type", "description", "masked", "node_id", "node_type", "remediation_ansible", "remediation_puppet", "remediation_script", "resource", "scan_id", "status", "test_category", "test_desc", "test_number", "test_rationale", "test_severity", "type", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        compliance_check_type: typing.Union[MetaOapg.properties.compliance_check_type, str, schemas.Unset] = schemas.unset,
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        masked: typing.Union[MetaOapg.properties.masked, bool, schemas.Unset] = schemas.unset,
        node_id: typing.Union[MetaOapg.properties.node_id, str, schemas.Unset] = schemas.unset,
        node_type: typing.Union[MetaOapg.properties.node_type, str, schemas.Unset] = schemas.unset,
        remediation_ansible: typing.Union[MetaOapg.properties.remediation_ansible, str, schemas.Unset] = schemas.unset,
        remediation_puppet: typing.Union[MetaOapg.properties.remediation_puppet, str, schemas.Unset] = schemas.unset,
        remediation_script: typing.Union[MetaOapg.properties.remediation_script, str, schemas.Unset] = schemas.unset,
        resource: typing.Union[MetaOapg.properties.resource, str, schemas.Unset] = schemas.unset,
        scan_id: typing.Union[MetaOapg.properties.scan_id, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        test_category: typing.Union[MetaOapg.properties.test_category, str, schemas.Unset] = schemas.unset,
        test_desc: typing.Union[MetaOapg.properties.test_desc, str, schemas.Unset] = schemas.unset,
        test_number: typing.Union[MetaOapg.properties.test_number, str, schemas.Unset] = schemas.unset,
        test_rationale: typing.Union[MetaOapg.properties.test_rationale, str, schemas.Unset] = schemas.unset,
        test_severity: typing.Union[MetaOapg.properties.test_severity, str, schemas.Unset] = schemas.unset,
        type: typing.Union[MetaOapg.properties.type, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'IngestersCompliance':
        return super().__new__(
            cls,
            *_args,
            compliance_check_type=compliance_check_type,
            description=description,
            masked=masked,
            node_id=node_id,
            node_type=node_type,
            remediation_ansible=remediation_ansible,
            remediation_puppet=remediation_puppet,
            remediation_script=remediation_script,
            resource=resource,
            scan_id=scan_id,
            status=status,
            test_category=test_category,
            test_desc=test_desc,
            test_number=test_number,
            test_rationale=test_rationale,
            test_severity=test_severity,
            type=type,
            _configuration=_configuration,
            **kwargs,
        )
