# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class IngestersSecret(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            timestamp = schemas.DateTimeSchema
            ImageLayerId = schemas.StrSchema
            
            
            class Match(
                schemas.DictSchema
            ):
            
            
                class MetaOapg:
                    
                    class properties:
                        full_filename = schemas.StrSchema
                        matched_content = schemas.StrSchema
                        relative_ending_index = schemas.IntSchema
                        relative_starting_index = schemas.IntSchema
                        starting_index = schemas.IntSchema
                        __annotations__ = {
                            "full_filename": full_filename,
                            "matched_content": matched_content,
                            "relative_ending_index": relative_ending_index,
                            "relative_starting_index": relative_starting_index,
                            "starting_index": starting_index,
                        }
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["full_filename"]) -> MetaOapg.properties.full_filename: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["matched_content"]) -> MetaOapg.properties.matched_content: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["relative_ending_index"]) -> MetaOapg.properties.relative_ending_index: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["relative_starting_index"]) -> MetaOapg.properties.relative_starting_index: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["starting_index"]) -> MetaOapg.properties.starting_index: ...
                
                @typing.overload
                def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                
                def __getitem__(self, name: typing.Union[typing_extensions.Literal["full_filename", "matched_content", "relative_ending_index", "relative_starting_index", "starting_index", ], str]):
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["full_filename"]) -> typing.Union[MetaOapg.properties.full_filename, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["matched_content"]) -> typing.Union[MetaOapg.properties.matched_content, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["relative_ending_index"]) -> typing.Union[MetaOapg.properties.relative_ending_index, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["relative_starting_index"]) -> typing.Union[MetaOapg.properties.relative_starting_index, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["starting_index"]) -> typing.Union[MetaOapg.properties.starting_index, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                
                def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["full_filename", "matched_content", "relative_ending_index", "relative_starting_index", "starting_index", ], str]):
                    return super().get_item_oapg(name)
                
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, ],
                    full_filename: typing.Union[MetaOapg.properties.full_filename, str, schemas.Unset] = schemas.unset,
                    matched_content: typing.Union[MetaOapg.properties.matched_content, str, schemas.Unset] = schemas.unset,
                    relative_ending_index: typing.Union[MetaOapg.properties.relative_ending_index, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                    relative_starting_index: typing.Union[MetaOapg.properties.relative_starting_index, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                    starting_index: typing.Union[MetaOapg.properties.starting_index, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'Match':
                    return super().__new__(
                        cls,
                        *_args,
                        full_filename=full_filename,
                        matched_content=matched_content,
                        relative_ending_index=relative_ending_index,
                        relative_starting_index=relative_starting_index,
                        starting_index=starting_index,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class Rule(
                schemas.DictSchema
            ):
            
            
                class MetaOapg:
                    
                    class properties:
                        id = schemas.IntSchema
                        name = schemas.StrSchema
                        part = schemas.StrSchema
                        signature_to_match = schemas.StrSchema
                        __annotations__ = {
                            "id": id,
                            "name": name,
                            "part": part,
                            "signature_to_match": signature_to_match,
                        }
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["part"]) -> MetaOapg.properties.part: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["signature_to_match"]) -> MetaOapg.properties.signature_to_match: ...
                
                @typing.overload
                def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                
                def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "name", "part", "signature_to_match", ], str]):
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["part"]) -> typing.Union[MetaOapg.properties.part, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["signature_to_match"]) -> typing.Union[MetaOapg.properties.signature_to_match, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                
                def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "name", "part", "signature_to_match", ], str]):
                    return super().get_item_oapg(name)
                
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, ],
                    id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                    name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
                    part: typing.Union[MetaOapg.properties.part, str, schemas.Unset] = schemas.unset,
                    signature_to_match: typing.Union[MetaOapg.properties.signature_to_match, str, schemas.Unset] = schemas.unset,
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'Rule':
                    return super().__new__(
                        cls,
                        *_args,
                        id=id,
                        name=name,
                        part=part,
                        signature_to_match=signature_to_match,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class Severity(
                schemas.DictSchema
            ):
            
            
                class MetaOapg:
                    
                    class properties:
                        level = schemas.StrSchema
                        score = schemas.NumberSchema
                        __annotations__ = {
                            "level": level,
                            "score": score,
                        }
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["level"]) -> MetaOapg.properties.level: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["score"]) -> MetaOapg.properties.score: ...
                
                @typing.overload
                def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                
                def __getitem__(self, name: typing.Union[typing_extensions.Literal["level", "score", ], str]):
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["level"]) -> typing.Union[MetaOapg.properties.level, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["score"]) -> typing.Union[MetaOapg.properties.score, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                
                def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["level", "score", ], str]):
                    return super().get_item_oapg(name)
                
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, ],
                    level: typing.Union[MetaOapg.properties.level, str, schemas.Unset] = schemas.unset,
                    score: typing.Union[MetaOapg.properties.score, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'Severity':
                    return super().__new__(
                        cls,
                        *_args,
                        level=level,
                        score=score,
                        _configuration=_configuration,
                        **kwargs,
                    )
            masked = schemas.BoolSchema
            scan_id = schemas.StrSchema
            __annotations__ = {
                "@timestamp": timestamp,
                "ImageLayerId": ImageLayerId,
                "Match": Match,
                "Rule": Rule,
                "Severity": Severity,
                "masked": masked,
                "scan_id": scan_id,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["@timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ImageLayerId"]) -> MetaOapg.properties.ImageLayerId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Match"]) -> MetaOapg.properties.Match: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Rule"]) -> MetaOapg.properties.Rule: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Severity"]) -> MetaOapg.properties.Severity: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["masked"]) -> MetaOapg.properties.masked: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scan_id"]) -> MetaOapg.properties.scan_id: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["@timestamp", "ImageLayerId", "Match", "Rule", "Severity", "masked", "scan_id", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["@timestamp"]) -> typing.Union[MetaOapg.properties.timestamp, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ImageLayerId"]) -> typing.Union[MetaOapg.properties.ImageLayerId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Match"]) -> typing.Union[MetaOapg.properties.Match, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Rule"]) -> typing.Union[MetaOapg.properties.Rule, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Severity"]) -> typing.Union[MetaOapg.properties.Severity, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["masked"]) -> typing.Union[MetaOapg.properties.masked, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scan_id"]) -> typing.Union[MetaOapg.properties.scan_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["@timestamp", "ImageLayerId", "Match", "Rule", "Severity", "masked", "scan_id", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        ImageLayerId: typing.Union[MetaOapg.properties.ImageLayerId, str, schemas.Unset] = schemas.unset,
        Match: typing.Union[MetaOapg.properties.Match, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        Rule: typing.Union[MetaOapg.properties.Rule, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        Severity: typing.Union[MetaOapg.properties.Severity, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        masked: typing.Union[MetaOapg.properties.masked, bool, schemas.Unset] = schemas.unset,
        scan_id: typing.Union[MetaOapg.properties.scan_id, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'IngestersSecret':
        return super().__new__(
            cls,
            *_args,
            ImageLayerId=ImageLayerId,
            Match=Match,
            Rule=Rule,
            Severity=Severity,
            masked=masked,
            scan_id=scan_id,
            _configuration=_configuration,
            **kwargs,
        )
