# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class ModelProcess(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "memory_max",
            "cmdline",
            "cpu_max",
            "node_name",
            "memory_usage",
            "open_files_count",
            "threads",
            "pid",
            "cpu_usage",
            "node_id",
            "ppid",
        }
        
        class properties:
            cmdline = schemas.StrSchema
            cpu_max = schemas.NumberSchema
            cpu_usage = schemas.NumberSchema
            memory_max = schemas.IntSchema
            memory_usage = schemas.IntSchema
            node_id = schemas.StrSchema
            node_name = schemas.StrSchema
            open_files_count = schemas.IntSchema
            pid = schemas.IntSchema
            ppid = schemas.IntSchema
            threads = schemas.IntSchema
            __annotations__ = {
                "cmdline": cmdline,
                "cpu_max": cpu_max,
                "cpu_usage": cpu_usage,
                "memory_max": memory_max,
                "memory_usage": memory_usage,
                "node_id": node_id,
                "node_name": node_name,
                "open_files_count": open_files_count,
                "pid": pid,
                "ppid": ppid,
                "threads": threads,
            }
    
    memory_max: MetaOapg.properties.memory_max
    cmdline: MetaOapg.properties.cmdline
    cpu_max: MetaOapg.properties.cpu_max
    node_name: MetaOapg.properties.node_name
    memory_usage: MetaOapg.properties.memory_usage
    open_files_count: MetaOapg.properties.open_files_count
    threads: MetaOapg.properties.threads
    pid: MetaOapg.properties.pid
    cpu_usage: MetaOapg.properties.cpu_usage
    node_id: MetaOapg.properties.node_id
    ppid: MetaOapg.properties.ppid
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cmdline"]) -> MetaOapg.properties.cmdline: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cpu_max"]) -> MetaOapg.properties.cpu_max: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cpu_usage"]) -> MetaOapg.properties.cpu_usage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["memory_max"]) -> MetaOapg.properties.memory_max: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["memory_usage"]) -> MetaOapg.properties.memory_usage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_id"]) -> MetaOapg.properties.node_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_name"]) -> MetaOapg.properties.node_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["open_files_count"]) -> MetaOapg.properties.open_files_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pid"]) -> MetaOapg.properties.pid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ppid"]) -> MetaOapg.properties.ppid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["threads"]) -> MetaOapg.properties.threads: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cmdline", "cpu_max", "cpu_usage", "memory_max", "memory_usage", "node_id", "node_name", "open_files_count", "pid", "ppid", "threads", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cmdline"]) -> MetaOapg.properties.cmdline: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cpu_max"]) -> MetaOapg.properties.cpu_max: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cpu_usage"]) -> MetaOapg.properties.cpu_usage: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["memory_max"]) -> MetaOapg.properties.memory_max: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["memory_usage"]) -> MetaOapg.properties.memory_usage: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_id"]) -> MetaOapg.properties.node_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_name"]) -> MetaOapg.properties.node_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["open_files_count"]) -> MetaOapg.properties.open_files_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pid"]) -> MetaOapg.properties.pid: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ppid"]) -> MetaOapg.properties.ppid: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["threads"]) -> MetaOapg.properties.threads: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cmdline", "cpu_max", "cpu_usage", "memory_max", "memory_usage", "node_id", "node_name", "open_files_count", "pid", "ppid", "threads", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        memory_max: typing.Union[MetaOapg.properties.memory_max, decimal.Decimal, int, ],
        cmdline: typing.Union[MetaOapg.properties.cmdline, str, ],
        cpu_max: typing.Union[MetaOapg.properties.cpu_max, decimal.Decimal, int, float, ],
        node_name: typing.Union[MetaOapg.properties.node_name, str, ],
        memory_usage: typing.Union[MetaOapg.properties.memory_usage, decimal.Decimal, int, ],
        open_files_count: typing.Union[MetaOapg.properties.open_files_count, decimal.Decimal, int, ],
        threads: typing.Union[MetaOapg.properties.threads, decimal.Decimal, int, ],
        pid: typing.Union[MetaOapg.properties.pid, decimal.Decimal, int, ],
        cpu_usage: typing.Union[MetaOapg.properties.cpu_usage, decimal.Decimal, int, float, ],
        node_id: typing.Union[MetaOapg.properties.node_id, str, ],
        ppid: typing.Union[MetaOapg.properties.ppid, decimal.Decimal, int, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelProcess':
        return super().__new__(
            cls,
            *_args,
            memory_max=memory_max,
            cmdline=cmdline,
            cpu_max=cpu_max,
            node_name=node_name,
            memory_usage=memory_usage,
            open_files_count=open_files_count,
            threads=threads,
            pid=pid,
            cpu_usage=cpu_usage,
            node_id=node_id,
            ppid=ppid,
            _configuration=_configuration,
            **kwargs,
        )
