# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class ModelPod(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "kubernetes_ip",
            "processes",
            "kubernetes_cluster_id",
            "kubernetes_cluster_name",
            "kubernetes_state",
            "node_name",
            "kubernetes_created",
            "pod_name",
            "kubernetes_namespace",
            "kubernetes_is_in_host_network",
            "kubernetes_labels",
            "containers",
            "host_name",
            "node_id",
        }
        
        class properties:
            
            
            class containers(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelContainer']:
                        return ModelContainer
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'containers':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            host_name = schemas.StrSchema
            kubernetes_cluster_id = schemas.StrSchema
            kubernetes_cluster_name = schemas.StrSchema
            kubernetes_created = schemas.StrSchema
            kubernetes_ip = schemas.StrSchema
            kubernetes_is_in_host_network = schemas.BoolSchema
            
            
            class kubernetes_labels(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.AnyTypeSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                ) -> 'kubernetes_labels':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            kubernetes_namespace = schemas.StrSchema
            kubernetes_state = schemas.StrSchema
            node_id = schemas.StrSchema
            node_name = schemas.StrSchema
            pod_name = schemas.StrSchema
            
            
            class processes(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelProcess']:
                        return ModelProcess
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'processes':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "containers": containers,
                "host_name": host_name,
                "kubernetes_cluster_id": kubernetes_cluster_id,
                "kubernetes_cluster_name": kubernetes_cluster_name,
                "kubernetes_created": kubernetes_created,
                "kubernetes_ip": kubernetes_ip,
                "kubernetes_is_in_host_network": kubernetes_is_in_host_network,
                "kubernetes_labels": kubernetes_labels,
                "kubernetes_namespace": kubernetes_namespace,
                "kubernetes_state": kubernetes_state,
                "node_id": node_id,
                "node_name": node_name,
                "pod_name": pod_name,
                "processes": processes,
            }
    
    kubernetes_ip: MetaOapg.properties.kubernetes_ip
    processes: MetaOapg.properties.processes
    kubernetes_cluster_id: MetaOapg.properties.kubernetes_cluster_id
    kubernetes_cluster_name: MetaOapg.properties.kubernetes_cluster_name
    kubernetes_state: MetaOapg.properties.kubernetes_state
    node_name: MetaOapg.properties.node_name
    kubernetes_created: MetaOapg.properties.kubernetes_created
    pod_name: MetaOapg.properties.pod_name
    kubernetes_namespace: MetaOapg.properties.kubernetes_namespace
    kubernetes_is_in_host_network: MetaOapg.properties.kubernetes_is_in_host_network
    kubernetes_labels: MetaOapg.properties.kubernetes_labels
    containers: MetaOapg.properties.containers
    host_name: MetaOapg.properties.host_name
    node_id: MetaOapg.properties.node_id
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["containers"]) -> MetaOapg.properties.containers: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["host_name"]) -> MetaOapg.properties.host_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_cluster_id"]) -> MetaOapg.properties.kubernetes_cluster_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_cluster_name"]) -> MetaOapg.properties.kubernetes_cluster_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_created"]) -> MetaOapg.properties.kubernetes_created: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_ip"]) -> MetaOapg.properties.kubernetes_ip: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_is_in_host_network"]) -> MetaOapg.properties.kubernetes_is_in_host_network: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_labels"]) -> MetaOapg.properties.kubernetes_labels: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_namespace"]) -> MetaOapg.properties.kubernetes_namespace: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_state"]) -> MetaOapg.properties.kubernetes_state: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_id"]) -> MetaOapg.properties.node_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_name"]) -> MetaOapg.properties.node_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pod_name"]) -> MetaOapg.properties.pod_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["processes"]) -> MetaOapg.properties.processes: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["containers", "host_name", "kubernetes_cluster_id", "kubernetes_cluster_name", "kubernetes_created", "kubernetes_ip", "kubernetes_is_in_host_network", "kubernetes_labels", "kubernetes_namespace", "kubernetes_state", "node_id", "node_name", "pod_name", "processes", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["containers"]) -> MetaOapg.properties.containers: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["host_name"]) -> MetaOapg.properties.host_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_cluster_id"]) -> MetaOapg.properties.kubernetes_cluster_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_cluster_name"]) -> MetaOapg.properties.kubernetes_cluster_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_created"]) -> MetaOapg.properties.kubernetes_created: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_ip"]) -> MetaOapg.properties.kubernetes_ip: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_is_in_host_network"]) -> MetaOapg.properties.kubernetes_is_in_host_network: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_labels"]) -> MetaOapg.properties.kubernetes_labels: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_namespace"]) -> MetaOapg.properties.kubernetes_namespace: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_state"]) -> MetaOapg.properties.kubernetes_state: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_id"]) -> MetaOapg.properties.node_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_name"]) -> MetaOapg.properties.node_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pod_name"]) -> MetaOapg.properties.pod_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["processes"]) -> MetaOapg.properties.processes: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["containers", "host_name", "kubernetes_cluster_id", "kubernetes_cluster_name", "kubernetes_created", "kubernetes_ip", "kubernetes_is_in_host_network", "kubernetes_labels", "kubernetes_namespace", "kubernetes_state", "node_id", "node_name", "pod_name", "processes", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        kubernetes_ip: typing.Union[MetaOapg.properties.kubernetes_ip, str, ],
        processes: typing.Union[MetaOapg.properties.processes, list, tuple, None, ],
        kubernetes_cluster_id: typing.Union[MetaOapg.properties.kubernetes_cluster_id, str, ],
        kubernetes_cluster_name: typing.Union[MetaOapg.properties.kubernetes_cluster_name, str, ],
        kubernetes_state: typing.Union[MetaOapg.properties.kubernetes_state, str, ],
        node_name: typing.Union[MetaOapg.properties.node_name, str, ],
        kubernetes_created: typing.Union[MetaOapg.properties.kubernetes_created, str, ],
        pod_name: typing.Union[MetaOapg.properties.pod_name, str, ],
        kubernetes_namespace: typing.Union[MetaOapg.properties.kubernetes_namespace, str, ],
        kubernetes_is_in_host_network: typing.Union[MetaOapg.properties.kubernetes_is_in_host_network, bool, ],
        kubernetes_labels: typing.Union[MetaOapg.properties.kubernetes_labels, dict, frozendict.frozendict, None, ],
        containers: typing.Union[MetaOapg.properties.containers, list, tuple, None, ],
        host_name: typing.Union[MetaOapg.properties.host_name, str, ],
        node_id: typing.Union[MetaOapg.properties.node_id, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelPod':
        return super().__new__(
            cls,
            *_args,
            kubernetes_ip=kubernetes_ip,
            processes=processes,
            kubernetes_cluster_id=kubernetes_cluster_id,
            kubernetes_cluster_name=kubernetes_cluster_name,
            kubernetes_state=kubernetes_state,
            node_name=node_name,
            kubernetes_created=kubernetes_created,
            pod_name=pod_name,
            kubernetes_namespace=kubernetes_namespace,
            kubernetes_is_in_host_network=kubernetes_is_in_host_network,
            kubernetes_labels=kubernetes_labels,
            containers=containers,
            host_name=host_name,
            node_id=node_id,
            _configuration=_configuration,
            **kwargs,
        )

from threatmapper.model.model_container import ModelContainer
from threatmapper.model.model_process import ModelProcess
