# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class ModelCloudCompliance(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "severity",
            "reason",
            "control_id",
            "resource",
            "masked",
            "count",
            "node_name",
            "description",
            "cloud_provider",
            "title",
            "type",
            "compliance_check_type",
            "account_id",
            "updated_at",
            "service",
            "region",
            "group",
            "node_id",
            "status",
        }
        
        class properties:
            account_id = schemas.StrSchema
            cloud_provider = schemas.StrSchema
            compliance_check_type = schemas.StrSchema
            control_id = schemas.StrSchema
            count = schemas.IntSchema
            description = schemas.StrSchema
            group = schemas.StrSchema
            masked = schemas.BoolSchema
            node_id = schemas.StrSchema
            node_name = schemas.StrSchema
            reason = schemas.StrSchema
            region = schemas.StrSchema
            resource = schemas.StrSchema
            service = schemas.StrSchema
            severity = schemas.StrSchema
            status = schemas.StrSchema
            title = schemas.StrSchema
            type = schemas.StrSchema
            updated_at = schemas.IntSchema
            __annotations__ = {
                "account_id": account_id,
                "cloud_provider": cloud_provider,
                "compliance_check_type": compliance_check_type,
                "control_id": control_id,
                "count": count,
                "description": description,
                "group": group,
                "masked": masked,
                "node_id": node_id,
                "node_name": node_name,
                "reason": reason,
                "region": region,
                "resource": resource,
                "service": service,
                "severity": severity,
                "status": status,
                "title": title,
                "type": type,
                "updated_at": updated_at,
            }
    
    severity: MetaOapg.properties.severity
    reason: MetaOapg.properties.reason
    control_id: MetaOapg.properties.control_id
    resource: MetaOapg.properties.resource
    masked: MetaOapg.properties.masked
    count: MetaOapg.properties.count
    node_name: MetaOapg.properties.node_name
    description: MetaOapg.properties.description
    cloud_provider: MetaOapg.properties.cloud_provider
    title: MetaOapg.properties.title
    type: MetaOapg.properties.type
    compliance_check_type: MetaOapg.properties.compliance_check_type
    account_id: MetaOapg.properties.account_id
    updated_at: MetaOapg.properties.updated_at
    service: MetaOapg.properties.service
    region: MetaOapg.properties.region
    group: MetaOapg.properties.group
    node_id: MetaOapg.properties.node_id
    status: MetaOapg.properties.status
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["account_id"]) -> MetaOapg.properties.account_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cloud_provider"]) -> MetaOapg.properties.cloud_provider: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["compliance_check_type"]) -> MetaOapg.properties.compliance_check_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["control_id"]) -> MetaOapg.properties.control_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["count"]) -> MetaOapg.properties.count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["group"]) -> MetaOapg.properties.group: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["masked"]) -> MetaOapg.properties.masked: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_id"]) -> MetaOapg.properties.node_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_name"]) -> MetaOapg.properties.node_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reason"]) -> MetaOapg.properties.reason: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["region"]) -> MetaOapg.properties.region: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resource"]) -> MetaOapg.properties.resource: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["service"]) -> MetaOapg.properties.service: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["severity"]) -> MetaOapg.properties.severity: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updated_at"]) -> MetaOapg.properties.updated_at: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["account_id", "cloud_provider", "compliance_check_type", "control_id", "count", "description", "group", "masked", "node_id", "node_name", "reason", "region", "resource", "service", "severity", "status", "title", "type", "updated_at", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["account_id"]) -> MetaOapg.properties.account_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cloud_provider"]) -> MetaOapg.properties.cloud_provider: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["compliance_check_type"]) -> MetaOapg.properties.compliance_check_type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["control_id"]) -> MetaOapg.properties.control_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["count"]) -> MetaOapg.properties.count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["group"]) -> MetaOapg.properties.group: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["masked"]) -> MetaOapg.properties.masked: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_id"]) -> MetaOapg.properties.node_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_name"]) -> MetaOapg.properties.node_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reason"]) -> MetaOapg.properties.reason: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["region"]) -> MetaOapg.properties.region: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resource"]) -> MetaOapg.properties.resource: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["service"]) -> MetaOapg.properties.service: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["severity"]) -> MetaOapg.properties.severity: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updated_at"]) -> MetaOapg.properties.updated_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["account_id", "cloud_provider", "compliance_check_type", "control_id", "count", "description", "group", "masked", "node_id", "node_name", "reason", "region", "resource", "service", "severity", "status", "title", "type", "updated_at", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        severity: typing.Union[MetaOapg.properties.severity, str, ],
        reason: typing.Union[MetaOapg.properties.reason, str, ],
        control_id: typing.Union[MetaOapg.properties.control_id, str, ],
        resource: typing.Union[MetaOapg.properties.resource, str, ],
        masked: typing.Union[MetaOapg.properties.masked, bool, ],
        count: typing.Union[MetaOapg.properties.count, decimal.Decimal, int, ],
        node_name: typing.Union[MetaOapg.properties.node_name, str, ],
        description: typing.Union[MetaOapg.properties.description, str, ],
        cloud_provider: typing.Union[MetaOapg.properties.cloud_provider, str, ],
        title: typing.Union[MetaOapg.properties.title, str, ],
        type: typing.Union[MetaOapg.properties.type, str, ],
        compliance_check_type: typing.Union[MetaOapg.properties.compliance_check_type, str, ],
        account_id: typing.Union[MetaOapg.properties.account_id, str, ],
        updated_at: typing.Union[MetaOapg.properties.updated_at, decimal.Decimal, int, ],
        service: typing.Union[MetaOapg.properties.service, str, ],
        region: typing.Union[MetaOapg.properties.region, str, ],
        group: typing.Union[MetaOapg.properties.group, str, ],
        node_id: typing.Union[MetaOapg.properties.node_id, str, ],
        status: typing.Union[MetaOapg.properties.status, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelCloudCompliance':
        return super().__new__(
            cls,
            *_args,
            severity=severity,
            reason=reason,
            control_id=control_id,
            resource=resource,
            masked=masked,
            count=count,
            node_name=node_name,
            description=description,
            cloud_provider=cloud_provider,
            title=title,
            type=type,
            compliance_check_type=compliance_check_type,
            account_id=account_id,
            updated_at=updated_at,
            service=service,
            region=region,
            group=group,
            node_id=node_id,
            status=status,
            _configuration=_configuration,
            **kwargs,
        )
