# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class ModelHost(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "vulnerabilities_count",
            "public_ip",
            "secrets_count",
            "cloud_region",
            "container_images",
            "cpu_max",
            "memory_usage",
            "private_ip",
            "secret_latest_scan_id",
            "vulnerability_latest_scan_id",
            "resource_group",
            "malware_scan_status",
            "inbound_connections",
            "availability_zone",
            "is_console_vm",
            "processes",
            "secret_scan_status",
            "compliance_scan_status",
            "outbound_connections",
            "os",
            "local_cidr",
            "malware_latest_scan_id",
            "malwares_count",
            "node_name",
            "cloud_provider",
            "agent_running",
            "version",
            "uptime",
            "memory_max",
            "instance_id",
            "kernel_id",
            "compliances_count",
            "kernel_version",
            "compliance_latest_scan_id",
            "containers",
            "pods",
            "cpu_usage",
            "instance_type",
            "vulnerability_scan_status",
            "host_name",
            "local_networks",
            "node_id",
        }
        
        class properties:
            agent_running = schemas.BoolSchema
            availability_zone = schemas.StrSchema
            cloud_provider = schemas.StrSchema
            cloud_region = schemas.StrSchema
            compliance_latest_scan_id = schemas.StrSchema
            compliance_scan_status = schemas.StrSchema
            compliances_count = schemas.IntSchema
            
            
            class container_images(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelContainerImage']:
                        return ModelContainerImage
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'container_images':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class containers(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelContainer']:
                        return ModelContainer
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'containers':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            cpu_max = schemas.NumberSchema
            cpu_usage = schemas.NumberSchema
            host_name = schemas.StrSchema
            
            
            class inbound_connections(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelConnection']:
                        return ModelConnection
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'inbound_connections':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            instance_id = schemas.StrSchema
            instance_type = schemas.StrSchema
            is_console_vm = schemas.BoolSchema
            kernel_id = schemas.StrSchema
            kernel_version = schemas.StrSchema
            
            
            class local_cidr(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    items = schemas.AnyTypeSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'local_cidr':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class local_networks(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    items = schemas.AnyTypeSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'local_networks':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            malware_latest_scan_id = schemas.StrSchema
            malware_scan_status = schemas.StrSchema
            malwares_count = schemas.IntSchema
            memory_max = schemas.IntSchema
            memory_usage = schemas.IntSchema
            node_id = schemas.StrSchema
            node_name = schemas.StrSchema
            os = schemas.StrSchema
            
            
            class outbound_connections(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelConnection']:
                        return ModelConnection
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'outbound_connections':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class pods(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelPod']:
                        return ModelPod
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'pods':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class private_ip(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    items = schemas.AnyTypeSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'private_ip':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class processes(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelProcess']:
                        return ModelProcess
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'processes':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class public_ip(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    items = schemas.AnyTypeSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'public_ip':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            resource_group = schemas.StrSchema
            secret_latest_scan_id = schemas.StrSchema
            secret_scan_status = schemas.StrSchema
            secrets_count = schemas.IntSchema
            uptime = schemas.IntSchema
            version = schemas.StrSchema
            vulnerabilities_count = schemas.IntSchema
            vulnerability_latest_scan_id = schemas.StrSchema
            vulnerability_scan_status = schemas.StrSchema
            __annotations__ = {
                "agent_running": agent_running,
                "availability_zone": availability_zone,
                "cloud_provider": cloud_provider,
                "cloud_region": cloud_region,
                "compliance_latest_scan_id": compliance_latest_scan_id,
                "compliance_scan_status": compliance_scan_status,
                "compliances_count": compliances_count,
                "container_images": container_images,
                "containers": containers,
                "cpu_max": cpu_max,
                "cpu_usage": cpu_usage,
                "host_name": host_name,
                "inbound_connections": inbound_connections,
                "instance_id": instance_id,
                "instance_type": instance_type,
                "is_console_vm": is_console_vm,
                "kernel_id": kernel_id,
                "kernel_version": kernel_version,
                "local_cidr": local_cidr,
                "local_networks": local_networks,
                "malware_latest_scan_id": malware_latest_scan_id,
                "malware_scan_status": malware_scan_status,
                "malwares_count": malwares_count,
                "memory_max": memory_max,
                "memory_usage": memory_usage,
                "node_id": node_id,
                "node_name": node_name,
                "os": os,
                "outbound_connections": outbound_connections,
                "pods": pods,
                "private_ip": private_ip,
                "processes": processes,
                "public_ip": public_ip,
                "resource_group": resource_group,
                "secret_latest_scan_id": secret_latest_scan_id,
                "secret_scan_status": secret_scan_status,
                "secrets_count": secrets_count,
                "uptime": uptime,
                "version": version,
                "vulnerabilities_count": vulnerabilities_count,
                "vulnerability_latest_scan_id": vulnerability_latest_scan_id,
                "vulnerability_scan_status": vulnerability_scan_status,
            }
    
    vulnerabilities_count: MetaOapg.properties.vulnerabilities_count
    public_ip: MetaOapg.properties.public_ip
    secrets_count: MetaOapg.properties.secrets_count
    cloud_region: MetaOapg.properties.cloud_region
    container_images: MetaOapg.properties.container_images
    cpu_max: MetaOapg.properties.cpu_max
    memory_usage: MetaOapg.properties.memory_usage
    private_ip: MetaOapg.properties.private_ip
    secret_latest_scan_id: MetaOapg.properties.secret_latest_scan_id
    vulnerability_latest_scan_id: MetaOapg.properties.vulnerability_latest_scan_id
    resource_group: MetaOapg.properties.resource_group
    malware_scan_status: MetaOapg.properties.malware_scan_status
    inbound_connections: MetaOapg.properties.inbound_connections
    availability_zone: MetaOapg.properties.availability_zone
    is_console_vm: MetaOapg.properties.is_console_vm
    processes: MetaOapg.properties.processes
    secret_scan_status: MetaOapg.properties.secret_scan_status
    compliance_scan_status: MetaOapg.properties.compliance_scan_status
    outbound_connections: MetaOapg.properties.outbound_connections
    os: MetaOapg.properties.os
    local_cidr: MetaOapg.properties.local_cidr
    malware_latest_scan_id: MetaOapg.properties.malware_latest_scan_id
    malwares_count: MetaOapg.properties.malwares_count
    node_name: MetaOapg.properties.node_name
    cloud_provider: MetaOapg.properties.cloud_provider
    agent_running: MetaOapg.properties.agent_running
    version: MetaOapg.properties.version
    uptime: MetaOapg.properties.uptime
    memory_max: MetaOapg.properties.memory_max
    instance_id: MetaOapg.properties.instance_id
    kernel_id: MetaOapg.properties.kernel_id
    compliances_count: MetaOapg.properties.compliances_count
    kernel_version: MetaOapg.properties.kernel_version
    compliance_latest_scan_id: MetaOapg.properties.compliance_latest_scan_id
    containers: MetaOapg.properties.containers
    pods: MetaOapg.properties.pods
    cpu_usage: MetaOapg.properties.cpu_usage
    instance_type: MetaOapg.properties.instance_type
    vulnerability_scan_status: MetaOapg.properties.vulnerability_scan_status
    host_name: MetaOapg.properties.host_name
    local_networks: MetaOapg.properties.local_networks
    node_id: MetaOapg.properties.node_id
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["agent_running"]) -> MetaOapg.properties.agent_running: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["availability_zone"]) -> MetaOapg.properties.availability_zone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cloud_provider"]) -> MetaOapg.properties.cloud_provider: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cloud_region"]) -> MetaOapg.properties.cloud_region: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["compliance_latest_scan_id"]) -> MetaOapg.properties.compliance_latest_scan_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["compliance_scan_status"]) -> MetaOapg.properties.compliance_scan_status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["compliances_count"]) -> MetaOapg.properties.compliances_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["container_images"]) -> MetaOapg.properties.container_images: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["containers"]) -> MetaOapg.properties.containers: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cpu_max"]) -> MetaOapg.properties.cpu_max: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cpu_usage"]) -> MetaOapg.properties.cpu_usage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["host_name"]) -> MetaOapg.properties.host_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["inbound_connections"]) -> MetaOapg.properties.inbound_connections: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["instance_id"]) -> MetaOapg.properties.instance_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["instance_type"]) -> MetaOapg.properties.instance_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_console_vm"]) -> MetaOapg.properties.is_console_vm: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kernel_id"]) -> MetaOapg.properties.kernel_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kernel_version"]) -> MetaOapg.properties.kernel_version: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["local_cidr"]) -> MetaOapg.properties.local_cidr: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["local_networks"]) -> MetaOapg.properties.local_networks: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["malware_latest_scan_id"]) -> MetaOapg.properties.malware_latest_scan_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["malware_scan_status"]) -> MetaOapg.properties.malware_scan_status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["malwares_count"]) -> MetaOapg.properties.malwares_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["memory_max"]) -> MetaOapg.properties.memory_max: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["memory_usage"]) -> MetaOapg.properties.memory_usage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_id"]) -> MetaOapg.properties.node_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_name"]) -> MetaOapg.properties.node_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["os"]) -> MetaOapg.properties.os: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["outbound_connections"]) -> MetaOapg.properties.outbound_connections: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pods"]) -> MetaOapg.properties.pods: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["private_ip"]) -> MetaOapg.properties.private_ip: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["processes"]) -> MetaOapg.properties.processes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["public_ip"]) -> MetaOapg.properties.public_ip: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resource_group"]) -> MetaOapg.properties.resource_group: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["secret_latest_scan_id"]) -> MetaOapg.properties.secret_latest_scan_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["secret_scan_status"]) -> MetaOapg.properties.secret_scan_status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["secrets_count"]) -> MetaOapg.properties.secrets_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["uptime"]) -> MetaOapg.properties.uptime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["version"]) -> MetaOapg.properties.version: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vulnerabilities_count"]) -> MetaOapg.properties.vulnerabilities_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vulnerability_latest_scan_id"]) -> MetaOapg.properties.vulnerability_latest_scan_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vulnerability_scan_status"]) -> MetaOapg.properties.vulnerability_scan_status: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["agent_running", "availability_zone", "cloud_provider", "cloud_region", "compliance_latest_scan_id", "compliance_scan_status", "compliances_count", "container_images", "containers", "cpu_max", "cpu_usage", "host_name", "inbound_connections", "instance_id", "instance_type", "is_console_vm", "kernel_id", "kernel_version", "local_cidr", "local_networks", "malware_latest_scan_id", "malware_scan_status", "malwares_count", "memory_max", "memory_usage", "node_id", "node_name", "os", "outbound_connections", "pods", "private_ip", "processes", "public_ip", "resource_group", "secret_latest_scan_id", "secret_scan_status", "secrets_count", "uptime", "version", "vulnerabilities_count", "vulnerability_latest_scan_id", "vulnerability_scan_status", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["agent_running"]) -> MetaOapg.properties.agent_running: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["availability_zone"]) -> MetaOapg.properties.availability_zone: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cloud_provider"]) -> MetaOapg.properties.cloud_provider: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cloud_region"]) -> MetaOapg.properties.cloud_region: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["compliance_latest_scan_id"]) -> MetaOapg.properties.compliance_latest_scan_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["compliance_scan_status"]) -> MetaOapg.properties.compliance_scan_status: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["compliances_count"]) -> MetaOapg.properties.compliances_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["container_images"]) -> MetaOapg.properties.container_images: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["containers"]) -> MetaOapg.properties.containers: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cpu_max"]) -> MetaOapg.properties.cpu_max: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cpu_usage"]) -> MetaOapg.properties.cpu_usage: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["host_name"]) -> MetaOapg.properties.host_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["inbound_connections"]) -> MetaOapg.properties.inbound_connections: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["instance_id"]) -> MetaOapg.properties.instance_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["instance_type"]) -> MetaOapg.properties.instance_type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_console_vm"]) -> MetaOapg.properties.is_console_vm: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kernel_id"]) -> MetaOapg.properties.kernel_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kernel_version"]) -> MetaOapg.properties.kernel_version: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["local_cidr"]) -> MetaOapg.properties.local_cidr: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["local_networks"]) -> MetaOapg.properties.local_networks: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["malware_latest_scan_id"]) -> MetaOapg.properties.malware_latest_scan_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["malware_scan_status"]) -> MetaOapg.properties.malware_scan_status: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["malwares_count"]) -> MetaOapg.properties.malwares_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["memory_max"]) -> MetaOapg.properties.memory_max: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["memory_usage"]) -> MetaOapg.properties.memory_usage: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_id"]) -> MetaOapg.properties.node_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_name"]) -> MetaOapg.properties.node_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["os"]) -> MetaOapg.properties.os: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["outbound_connections"]) -> MetaOapg.properties.outbound_connections: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pods"]) -> MetaOapg.properties.pods: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["private_ip"]) -> MetaOapg.properties.private_ip: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["processes"]) -> MetaOapg.properties.processes: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["public_ip"]) -> MetaOapg.properties.public_ip: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resource_group"]) -> MetaOapg.properties.resource_group: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["secret_latest_scan_id"]) -> MetaOapg.properties.secret_latest_scan_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["secret_scan_status"]) -> MetaOapg.properties.secret_scan_status: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["secrets_count"]) -> MetaOapg.properties.secrets_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["uptime"]) -> MetaOapg.properties.uptime: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["version"]) -> MetaOapg.properties.version: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vulnerabilities_count"]) -> MetaOapg.properties.vulnerabilities_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vulnerability_latest_scan_id"]) -> MetaOapg.properties.vulnerability_latest_scan_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vulnerability_scan_status"]) -> MetaOapg.properties.vulnerability_scan_status: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["agent_running", "availability_zone", "cloud_provider", "cloud_region", "compliance_latest_scan_id", "compliance_scan_status", "compliances_count", "container_images", "containers", "cpu_max", "cpu_usage", "host_name", "inbound_connections", "instance_id", "instance_type", "is_console_vm", "kernel_id", "kernel_version", "local_cidr", "local_networks", "malware_latest_scan_id", "malware_scan_status", "malwares_count", "memory_max", "memory_usage", "node_id", "node_name", "os", "outbound_connections", "pods", "private_ip", "processes", "public_ip", "resource_group", "secret_latest_scan_id", "secret_scan_status", "secrets_count", "uptime", "version", "vulnerabilities_count", "vulnerability_latest_scan_id", "vulnerability_scan_status", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        vulnerabilities_count: typing.Union[MetaOapg.properties.vulnerabilities_count, decimal.Decimal, int, ],
        public_ip: typing.Union[MetaOapg.properties.public_ip, list, tuple, None, ],
        secrets_count: typing.Union[MetaOapg.properties.secrets_count, decimal.Decimal, int, ],
        cloud_region: typing.Union[MetaOapg.properties.cloud_region, str, ],
        container_images: typing.Union[MetaOapg.properties.container_images, list, tuple, None, ],
        cpu_max: typing.Union[MetaOapg.properties.cpu_max, decimal.Decimal, int, float, ],
        memory_usage: typing.Union[MetaOapg.properties.memory_usage, decimal.Decimal, int, ],
        private_ip: typing.Union[MetaOapg.properties.private_ip, list, tuple, None, ],
        secret_latest_scan_id: typing.Union[MetaOapg.properties.secret_latest_scan_id, str, ],
        vulnerability_latest_scan_id: typing.Union[MetaOapg.properties.vulnerability_latest_scan_id, str, ],
        resource_group: typing.Union[MetaOapg.properties.resource_group, str, ],
        malware_scan_status: typing.Union[MetaOapg.properties.malware_scan_status, str, ],
        inbound_connections: typing.Union[MetaOapg.properties.inbound_connections, list, tuple, None, ],
        availability_zone: typing.Union[MetaOapg.properties.availability_zone, str, ],
        is_console_vm: typing.Union[MetaOapg.properties.is_console_vm, bool, ],
        processes: typing.Union[MetaOapg.properties.processes, list, tuple, None, ],
        secret_scan_status: typing.Union[MetaOapg.properties.secret_scan_status, str, ],
        compliance_scan_status: typing.Union[MetaOapg.properties.compliance_scan_status, str, ],
        outbound_connections: typing.Union[MetaOapg.properties.outbound_connections, list, tuple, None, ],
        os: typing.Union[MetaOapg.properties.os, str, ],
        local_cidr: typing.Union[MetaOapg.properties.local_cidr, list, tuple, None, ],
        malware_latest_scan_id: typing.Union[MetaOapg.properties.malware_latest_scan_id, str, ],
        malwares_count: typing.Union[MetaOapg.properties.malwares_count, decimal.Decimal, int, ],
        node_name: typing.Union[MetaOapg.properties.node_name, str, ],
        cloud_provider: typing.Union[MetaOapg.properties.cloud_provider, str, ],
        agent_running: typing.Union[MetaOapg.properties.agent_running, bool, ],
        version: typing.Union[MetaOapg.properties.version, str, ],
        uptime: typing.Union[MetaOapg.properties.uptime, decimal.Decimal, int, ],
        memory_max: typing.Union[MetaOapg.properties.memory_max, decimal.Decimal, int, ],
        instance_id: typing.Union[MetaOapg.properties.instance_id, str, ],
        kernel_id: typing.Union[MetaOapg.properties.kernel_id, str, ],
        compliances_count: typing.Union[MetaOapg.properties.compliances_count, decimal.Decimal, int, ],
        kernel_version: typing.Union[MetaOapg.properties.kernel_version, str, ],
        compliance_latest_scan_id: typing.Union[MetaOapg.properties.compliance_latest_scan_id, str, ],
        containers: typing.Union[MetaOapg.properties.containers, list, tuple, None, ],
        pods: typing.Union[MetaOapg.properties.pods, list, tuple, None, ],
        cpu_usage: typing.Union[MetaOapg.properties.cpu_usage, decimal.Decimal, int, float, ],
        instance_type: typing.Union[MetaOapg.properties.instance_type, str, ],
        vulnerability_scan_status: typing.Union[MetaOapg.properties.vulnerability_scan_status, str, ],
        host_name: typing.Union[MetaOapg.properties.host_name, str, ],
        local_networks: typing.Union[MetaOapg.properties.local_networks, list, tuple, None, ],
        node_id: typing.Union[MetaOapg.properties.node_id, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelHost':
        return super().__new__(
            cls,
            *_args,
            vulnerabilities_count=vulnerabilities_count,
            public_ip=public_ip,
            secrets_count=secrets_count,
            cloud_region=cloud_region,
            container_images=container_images,
            cpu_max=cpu_max,
            memory_usage=memory_usage,
            private_ip=private_ip,
            secret_latest_scan_id=secret_latest_scan_id,
            vulnerability_latest_scan_id=vulnerability_latest_scan_id,
            resource_group=resource_group,
            malware_scan_status=malware_scan_status,
            inbound_connections=inbound_connections,
            availability_zone=availability_zone,
            is_console_vm=is_console_vm,
            processes=processes,
            secret_scan_status=secret_scan_status,
            compliance_scan_status=compliance_scan_status,
            outbound_connections=outbound_connections,
            os=os,
            local_cidr=local_cidr,
            malware_latest_scan_id=malware_latest_scan_id,
            malwares_count=malwares_count,
            node_name=node_name,
            cloud_provider=cloud_provider,
            agent_running=agent_running,
            version=version,
            uptime=uptime,
            memory_max=memory_max,
            instance_id=instance_id,
            kernel_id=kernel_id,
            compliances_count=compliances_count,
            kernel_version=kernel_version,
            compliance_latest_scan_id=compliance_latest_scan_id,
            containers=containers,
            pods=pods,
            cpu_usage=cpu_usage,
            instance_type=instance_type,
            vulnerability_scan_status=vulnerability_scan_status,
            host_name=host_name,
            local_networks=local_networks,
            node_id=node_id,
            _configuration=_configuration,
            **kwargs,
        )

from threatmapper.model.model_connection import ModelConnection
from threatmapper.model.model_container import ModelContainer
from threatmapper.model.model_container_image import ModelContainerImage
from threatmapper.model.model_pod import ModelPod
from threatmapper.model.model_process import ModelProcess
