# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class ModelContainerImage(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "metadata",
            "secret_scan_status",
            "vulnerabilities_count",
            "secrets_count",
            "malware_latest_scan_id",
            "malwares_count",
            "node_name",
            "secret_latest_scan_id",
            "vulnerability_latest_scan_id",
            "docker_image_created_at",
            "docker_image_tag",
            "malware_scan_status",
            "docker_image_size",
            "docker_image_virtual_size",
            "containers",
            "docker_image_id",
            "vulnerability_scan_status",
            "docker_image_name",
            "node_id",
        }
        
        class properties:
            
            
            class containers(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelContainer']:
                        return ModelContainer
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'containers':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            docker_image_created_at = schemas.StrSchema
            docker_image_id = schemas.StrSchema
            docker_image_name = schemas.StrSchema
            docker_image_size = schemas.StrSchema
            docker_image_tag = schemas.StrSchema
            docker_image_virtual_size = schemas.StrSchema
            malware_latest_scan_id = schemas.StrSchema
            malware_scan_status = schemas.StrSchema
            malwares_count = schemas.IntSchema
        
            @staticmethod
            def metadata() -> typing.Type['ModelMetadata']:
                return ModelMetadata
            node_id = schemas.StrSchema
            node_name = schemas.StrSchema
            secret_latest_scan_id = schemas.StrSchema
            secret_scan_status = schemas.StrSchema
            secrets_count = schemas.IntSchema
            vulnerabilities_count = schemas.IntSchema
            vulnerability_latest_scan_id = schemas.StrSchema
            vulnerability_scan_status = schemas.StrSchema
            __annotations__ = {
                "containers": containers,
                "docker_image_created_at": docker_image_created_at,
                "docker_image_id": docker_image_id,
                "docker_image_name": docker_image_name,
                "docker_image_size": docker_image_size,
                "docker_image_tag": docker_image_tag,
                "docker_image_virtual_size": docker_image_virtual_size,
                "malware_latest_scan_id": malware_latest_scan_id,
                "malware_scan_status": malware_scan_status,
                "malwares_count": malwares_count,
                "metadata": metadata,
                "node_id": node_id,
                "node_name": node_name,
                "secret_latest_scan_id": secret_latest_scan_id,
                "secret_scan_status": secret_scan_status,
                "secrets_count": secrets_count,
                "vulnerabilities_count": vulnerabilities_count,
                "vulnerability_latest_scan_id": vulnerability_latest_scan_id,
                "vulnerability_scan_status": vulnerability_scan_status,
            }
    
    metadata: 'ModelMetadata'
    secret_scan_status: MetaOapg.properties.secret_scan_status
    vulnerabilities_count: MetaOapg.properties.vulnerabilities_count
    secrets_count: MetaOapg.properties.secrets_count
    malware_latest_scan_id: MetaOapg.properties.malware_latest_scan_id
    malwares_count: MetaOapg.properties.malwares_count
    node_name: MetaOapg.properties.node_name
    secret_latest_scan_id: MetaOapg.properties.secret_latest_scan_id
    vulnerability_latest_scan_id: MetaOapg.properties.vulnerability_latest_scan_id
    docker_image_created_at: MetaOapg.properties.docker_image_created_at
    docker_image_tag: MetaOapg.properties.docker_image_tag
    malware_scan_status: MetaOapg.properties.malware_scan_status
    docker_image_size: MetaOapg.properties.docker_image_size
    docker_image_virtual_size: MetaOapg.properties.docker_image_virtual_size
    containers: MetaOapg.properties.containers
    docker_image_id: MetaOapg.properties.docker_image_id
    vulnerability_scan_status: MetaOapg.properties.vulnerability_scan_status
    docker_image_name: MetaOapg.properties.docker_image_name
    node_id: MetaOapg.properties.node_id
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["containers"]) -> MetaOapg.properties.containers: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_image_created_at"]) -> MetaOapg.properties.docker_image_created_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_image_id"]) -> MetaOapg.properties.docker_image_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_image_name"]) -> MetaOapg.properties.docker_image_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_image_size"]) -> MetaOapg.properties.docker_image_size: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_image_tag"]) -> MetaOapg.properties.docker_image_tag: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_image_virtual_size"]) -> MetaOapg.properties.docker_image_virtual_size: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["malware_latest_scan_id"]) -> MetaOapg.properties.malware_latest_scan_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["malware_scan_status"]) -> MetaOapg.properties.malware_scan_status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["malwares_count"]) -> MetaOapg.properties.malwares_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> 'ModelMetadata': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_id"]) -> MetaOapg.properties.node_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_name"]) -> MetaOapg.properties.node_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["secret_latest_scan_id"]) -> MetaOapg.properties.secret_latest_scan_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["secret_scan_status"]) -> MetaOapg.properties.secret_scan_status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["secrets_count"]) -> MetaOapg.properties.secrets_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vulnerabilities_count"]) -> MetaOapg.properties.vulnerabilities_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vulnerability_latest_scan_id"]) -> MetaOapg.properties.vulnerability_latest_scan_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vulnerability_scan_status"]) -> MetaOapg.properties.vulnerability_scan_status: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["containers", "docker_image_created_at", "docker_image_id", "docker_image_name", "docker_image_size", "docker_image_tag", "docker_image_virtual_size", "malware_latest_scan_id", "malware_scan_status", "malwares_count", "metadata", "node_id", "node_name", "secret_latest_scan_id", "secret_scan_status", "secrets_count", "vulnerabilities_count", "vulnerability_latest_scan_id", "vulnerability_scan_status", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["containers"]) -> MetaOapg.properties.containers: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_image_created_at"]) -> MetaOapg.properties.docker_image_created_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_image_id"]) -> MetaOapg.properties.docker_image_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_image_name"]) -> MetaOapg.properties.docker_image_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_image_size"]) -> MetaOapg.properties.docker_image_size: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_image_tag"]) -> MetaOapg.properties.docker_image_tag: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_image_virtual_size"]) -> MetaOapg.properties.docker_image_virtual_size: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["malware_latest_scan_id"]) -> MetaOapg.properties.malware_latest_scan_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["malware_scan_status"]) -> MetaOapg.properties.malware_scan_status: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["malwares_count"]) -> MetaOapg.properties.malwares_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> 'ModelMetadata': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_id"]) -> MetaOapg.properties.node_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_name"]) -> MetaOapg.properties.node_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["secret_latest_scan_id"]) -> MetaOapg.properties.secret_latest_scan_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["secret_scan_status"]) -> MetaOapg.properties.secret_scan_status: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["secrets_count"]) -> MetaOapg.properties.secrets_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vulnerabilities_count"]) -> MetaOapg.properties.vulnerabilities_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vulnerability_latest_scan_id"]) -> MetaOapg.properties.vulnerability_latest_scan_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vulnerability_scan_status"]) -> MetaOapg.properties.vulnerability_scan_status: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["containers", "docker_image_created_at", "docker_image_id", "docker_image_name", "docker_image_size", "docker_image_tag", "docker_image_virtual_size", "malware_latest_scan_id", "malware_scan_status", "malwares_count", "metadata", "node_id", "node_name", "secret_latest_scan_id", "secret_scan_status", "secrets_count", "vulnerabilities_count", "vulnerability_latest_scan_id", "vulnerability_scan_status", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        metadata: 'ModelMetadata',
        secret_scan_status: typing.Union[MetaOapg.properties.secret_scan_status, str, ],
        vulnerabilities_count: typing.Union[MetaOapg.properties.vulnerabilities_count, decimal.Decimal, int, ],
        secrets_count: typing.Union[MetaOapg.properties.secrets_count, decimal.Decimal, int, ],
        malware_latest_scan_id: typing.Union[MetaOapg.properties.malware_latest_scan_id, str, ],
        malwares_count: typing.Union[MetaOapg.properties.malwares_count, decimal.Decimal, int, ],
        node_name: typing.Union[MetaOapg.properties.node_name, str, ],
        secret_latest_scan_id: typing.Union[MetaOapg.properties.secret_latest_scan_id, str, ],
        vulnerability_latest_scan_id: typing.Union[MetaOapg.properties.vulnerability_latest_scan_id, str, ],
        docker_image_created_at: typing.Union[MetaOapg.properties.docker_image_created_at, str, ],
        docker_image_tag: typing.Union[MetaOapg.properties.docker_image_tag, str, ],
        malware_scan_status: typing.Union[MetaOapg.properties.malware_scan_status, str, ],
        docker_image_size: typing.Union[MetaOapg.properties.docker_image_size, str, ],
        docker_image_virtual_size: typing.Union[MetaOapg.properties.docker_image_virtual_size, str, ],
        containers: typing.Union[MetaOapg.properties.containers, list, tuple, None, ],
        docker_image_id: typing.Union[MetaOapg.properties.docker_image_id, str, ],
        vulnerability_scan_status: typing.Union[MetaOapg.properties.vulnerability_scan_status, str, ],
        docker_image_name: typing.Union[MetaOapg.properties.docker_image_name, str, ],
        node_id: typing.Union[MetaOapg.properties.node_id, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelContainerImage':
        return super().__new__(
            cls,
            *_args,
            metadata=metadata,
            secret_scan_status=secret_scan_status,
            vulnerabilities_count=vulnerabilities_count,
            secrets_count=secrets_count,
            malware_latest_scan_id=malware_latest_scan_id,
            malwares_count=malwares_count,
            node_name=node_name,
            secret_latest_scan_id=secret_latest_scan_id,
            vulnerability_latest_scan_id=vulnerability_latest_scan_id,
            docker_image_created_at=docker_image_created_at,
            docker_image_tag=docker_image_tag,
            malware_scan_status=malware_scan_status,
            docker_image_size=docker_image_size,
            docker_image_virtual_size=docker_image_virtual_size,
            containers=containers,
            docker_image_id=docker_image_id,
            vulnerability_scan_status=vulnerability_scan_status,
            docker_image_name=docker_image_name,
            node_id=node_id,
            _configuration=_configuration,
            **kwargs,
        )

from threatmapper.model.model_container import ModelContainer
from threatmapper.model.model_metadata import ModelMetadata
