# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class ModelScanInfo(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "severity_counts",
            "status_message",
            "node_type",
            "updated_at",
            "node_name",
            "created_at",
            "scan_id",
            "node_id",
            "status",
        }
        
        class properties:
            created_at = schemas.Int64Schema
            node_id = schemas.StrSchema
            node_name = schemas.StrSchema
            node_type = schemas.StrSchema
            scan_id = schemas.StrSchema
            
            
            class severity_counts(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    additional_properties = schemas.IntSchema
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, decimal.Decimal, int, ],
                ) -> 'severity_counts':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            status = schemas.StrSchema
            status_message = schemas.StrSchema
            updated_at = schemas.Int64Schema
            __annotations__ = {
                "created_at": created_at,
                "node_id": node_id,
                "node_name": node_name,
                "node_type": node_type,
                "scan_id": scan_id,
                "severity_counts": severity_counts,
                "status": status,
                "status_message": status_message,
                "updated_at": updated_at,
            }
    
    severity_counts: MetaOapg.properties.severity_counts
    status_message: MetaOapg.properties.status_message
    node_type: MetaOapg.properties.node_type
    updated_at: MetaOapg.properties.updated_at
    node_name: MetaOapg.properties.node_name
    created_at: MetaOapg.properties.created_at
    scan_id: MetaOapg.properties.scan_id
    node_id: MetaOapg.properties.node_id
    status: MetaOapg.properties.status
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_at"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_id"]) -> MetaOapg.properties.node_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_name"]) -> MetaOapg.properties.node_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_type"]) -> MetaOapg.properties.node_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scan_id"]) -> MetaOapg.properties.scan_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["severity_counts"]) -> MetaOapg.properties.severity_counts: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status_message"]) -> MetaOapg.properties.status_message: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updated_at"]) -> MetaOapg.properties.updated_at: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["created_at", "node_id", "node_name", "node_type", "scan_id", "severity_counts", "status", "status_message", "updated_at", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_at"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_id"]) -> MetaOapg.properties.node_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_name"]) -> MetaOapg.properties.node_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_type"]) -> MetaOapg.properties.node_type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scan_id"]) -> MetaOapg.properties.scan_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["severity_counts"]) -> MetaOapg.properties.severity_counts: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status_message"]) -> MetaOapg.properties.status_message: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updated_at"]) -> MetaOapg.properties.updated_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["created_at", "node_id", "node_name", "node_type", "scan_id", "severity_counts", "status", "status_message", "updated_at", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        severity_counts: typing.Union[MetaOapg.properties.severity_counts, dict, frozendict.frozendict, None, ],
        status_message: typing.Union[MetaOapg.properties.status_message, str, ],
        node_type: typing.Union[MetaOapg.properties.node_type, str, ],
        updated_at: typing.Union[MetaOapg.properties.updated_at, decimal.Decimal, int, ],
        node_name: typing.Union[MetaOapg.properties.node_name, str, ],
        created_at: typing.Union[MetaOapg.properties.created_at, decimal.Decimal, int, ],
        scan_id: typing.Union[MetaOapg.properties.scan_id, str, ],
        node_id: typing.Union[MetaOapg.properties.node_id, str, ],
        status: typing.Union[MetaOapg.properties.status, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelScanInfo':
        return super().__new__(
            cls,
            *_args,
            severity_counts=severity_counts,
            status_message=status_message,
            node_type=node_type,
            updated_at=updated_at,
            node_name=node_name,
            created_at=created_at,
            scan_id=scan_id,
            node_id=node_id,
            status=status,
            _configuration=_configuration,
            **kwargs,
        )
