# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class ReportMetadata(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            agent_running = schemas.BoolSchema
            availability_zone = schemas.StrSchema
            cloud_provider = schemas.StrSchema
            cloud_region = schemas.StrSchema
            cmdline = schemas.StrSchema
            connection_count = schemas.IntSchema
            copy_of = schemas.StrSchema
            cpu_max = schemas.NumberSchema
            cpu_usage = schemas.NumberSchema
            docker_container_command = schemas.StrSchema
            docker_container_created = schemas.StrSchema
            
            
            class docker_container_ips(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'docker_container_ips':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            docker_container_name = schemas.StrSchema
            docker_container_network_mode = schemas.StrSchema
            docker_container_networks = schemas.StrSchema
            docker_container_ports = schemas.StrSchema
            docker_container_state = schemas.StrSchema
            docker_container_state_human = schemas.StrSchema
            docker_env = schemas.StrSchema
            docker_image_created_at = schemas.StrSchema
            docker_image_id = schemas.StrSchema
            docker_image_name = schemas.StrSchema
            docker_image_name_with_tag = schemas.StrSchema
            docker_image_size = schemas.StrSchema
            docker_image_tag = schemas.StrSchema
            docker_image_virtual_size = schemas.StrSchema
            docker_label = schemas.StrSchema
            host_name = schemas.StrSchema
            instance_id = schemas.StrSchema
            instance_type = schemas.StrSchema
            interface_ip_map = schemas.StrSchema
            
            
            class interface_ips(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'interface_ips':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class interface_names(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'interface_names':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            is_console_vm = schemas.BoolSchema
            kernel_id = schemas.StrSchema
            kernel_version = schemas.StrSchema
            kubernetes_cluster_id = schemas.StrSchema
            kubernetes_cluster_name = schemas.StrSchema
            kubernetes_created = schemas.StrSchema
            
            
            class kubernetes_ingress_ip(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'kubernetes_ingress_ip':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            kubernetes_ip = schemas.StrSchema
            kubernetes_is_in_host_network = schemas.BoolSchema
            kubernetes_labels = schemas.StrSchema
            kubernetes_namespace = schemas.StrSchema
            
            
            class kubernetes_ports(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'kubernetes_ports':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            kubernetes_public_ip = schemas.StrSchema
            kubernetes_state = schemas.StrSchema
            kubernetes_type = schemas.StrSchema
            
            
            class local_cidr(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'local_cidr':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class local_networks(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'local_networks':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            memory_max = schemas.IntSchema
            memory_usage = schemas.IntSchema
            node_id = schemas.StrSchema
            node_name = schemas.StrSchema
            node_type = schemas.StrSchema
            
            
            class open_files(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'open_files':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            open_files_count = schemas.IntSchema
            os = schemas.StrSchema
            pid = schemas.IntSchema
            pod_name = schemas.StrSchema
            ppid = schemas.IntSchema
            
            
            class private_ip(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'private_ip':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            pseudo = schemas.BoolSchema
            
            
            class public_ip(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'public_ip':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            resource_group = schemas.StrSchema
            threads = schemas.IntSchema
            timestamp = schemas.StrSchema
            uptime = schemas.IntSchema
            
            
            class user_defined_tags(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'user_defined_tags':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            version = schemas.StrSchema
            __annotations__ = {
                "agent_running": agent_running,
                "availability_zone": availability_zone,
                "cloud_provider": cloud_provider,
                "cloud_region": cloud_region,
                "cmdline": cmdline,
                "connection_count": connection_count,
                "copy_of": copy_of,
                "cpu_max": cpu_max,
                "cpu_usage": cpu_usage,
                "docker_container_command": docker_container_command,
                "docker_container_created": docker_container_created,
                "docker_container_ips": docker_container_ips,
                "docker_container_name": docker_container_name,
                "docker_container_network_mode": docker_container_network_mode,
                "docker_container_networks": docker_container_networks,
                "docker_container_ports": docker_container_ports,
                "docker_container_state": docker_container_state,
                "docker_container_state_human": docker_container_state_human,
                "docker_env": docker_env,
                "docker_image_created_at": docker_image_created_at,
                "docker_image_id": docker_image_id,
                "docker_image_name": docker_image_name,
                "docker_image_name_with_tag": docker_image_name_with_tag,
                "docker_image_size": docker_image_size,
                "docker_image_tag": docker_image_tag,
                "docker_image_virtual_size": docker_image_virtual_size,
                "docker_label": docker_label,
                "host_name": host_name,
                "instance_id": instance_id,
                "instance_type": instance_type,
                "interface_ip_map": interface_ip_map,
                "interface_ips": interface_ips,
                "interface_names": interface_names,
                "is_console_vm": is_console_vm,
                "kernel_id": kernel_id,
                "kernel_version": kernel_version,
                "kubernetes_cluster_id": kubernetes_cluster_id,
                "kubernetes_cluster_name": kubernetes_cluster_name,
                "kubernetes_created": kubernetes_created,
                "kubernetes_ingress_ip": kubernetes_ingress_ip,
                "kubernetes_ip": kubernetes_ip,
                "kubernetes_is_in_host_network": kubernetes_is_in_host_network,
                "kubernetes_labels": kubernetes_labels,
                "kubernetes_namespace": kubernetes_namespace,
                "kubernetes_ports": kubernetes_ports,
                "kubernetes_public_ip": kubernetes_public_ip,
                "kubernetes_state": kubernetes_state,
                "kubernetes_type": kubernetes_type,
                "local_cidr": local_cidr,
                "local_networks": local_networks,
                "memory_max": memory_max,
                "memory_usage": memory_usage,
                "node_id": node_id,
                "node_name": node_name,
                "node_type": node_type,
                "open_files": open_files,
                "open_files_count": open_files_count,
                "os": os,
                "pid": pid,
                "pod_name": pod_name,
                "ppid": ppid,
                "private_ip": private_ip,
                "pseudo": pseudo,
                "public_ip": public_ip,
                "resource_group": resource_group,
                "threads": threads,
                "timestamp": timestamp,
                "uptime": uptime,
                "user_defined_tags": user_defined_tags,
                "version": version,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["agent_running"]) -> MetaOapg.properties.agent_running: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["availability_zone"]) -> MetaOapg.properties.availability_zone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cloud_provider"]) -> MetaOapg.properties.cloud_provider: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cloud_region"]) -> MetaOapg.properties.cloud_region: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cmdline"]) -> MetaOapg.properties.cmdline: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["connection_count"]) -> MetaOapg.properties.connection_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["copy_of"]) -> MetaOapg.properties.copy_of: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cpu_max"]) -> MetaOapg.properties.cpu_max: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cpu_usage"]) -> MetaOapg.properties.cpu_usage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_container_command"]) -> MetaOapg.properties.docker_container_command: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_container_created"]) -> MetaOapg.properties.docker_container_created: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_container_ips"]) -> MetaOapg.properties.docker_container_ips: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_container_name"]) -> MetaOapg.properties.docker_container_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_container_network_mode"]) -> MetaOapg.properties.docker_container_network_mode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_container_networks"]) -> MetaOapg.properties.docker_container_networks: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_container_ports"]) -> MetaOapg.properties.docker_container_ports: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_container_state"]) -> MetaOapg.properties.docker_container_state: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_container_state_human"]) -> MetaOapg.properties.docker_container_state_human: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_env"]) -> MetaOapg.properties.docker_env: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_image_created_at"]) -> MetaOapg.properties.docker_image_created_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_image_id"]) -> MetaOapg.properties.docker_image_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_image_name"]) -> MetaOapg.properties.docker_image_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_image_name_with_tag"]) -> MetaOapg.properties.docker_image_name_with_tag: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_image_size"]) -> MetaOapg.properties.docker_image_size: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_image_tag"]) -> MetaOapg.properties.docker_image_tag: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_image_virtual_size"]) -> MetaOapg.properties.docker_image_virtual_size: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["docker_label"]) -> MetaOapg.properties.docker_label: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["host_name"]) -> MetaOapg.properties.host_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["instance_id"]) -> MetaOapg.properties.instance_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["instance_type"]) -> MetaOapg.properties.instance_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["interface_ip_map"]) -> MetaOapg.properties.interface_ip_map: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["interface_ips"]) -> MetaOapg.properties.interface_ips: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["interface_names"]) -> MetaOapg.properties.interface_names: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_console_vm"]) -> MetaOapg.properties.is_console_vm: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kernel_id"]) -> MetaOapg.properties.kernel_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kernel_version"]) -> MetaOapg.properties.kernel_version: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_cluster_id"]) -> MetaOapg.properties.kubernetes_cluster_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_cluster_name"]) -> MetaOapg.properties.kubernetes_cluster_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_created"]) -> MetaOapg.properties.kubernetes_created: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_ingress_ip"]) -> MetaOapg.properties.kubernetes_ingress_ip: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_ip"]) -> MetaOapg.properties.kubernetes_ip: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_is_in_host_network"]) -> MetaOapg.properties.kubernetes_is_in_host_network: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_labels"]) -> MetaOapg.properties.kubernetes_labels: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_namespace"]) -> MetaOapg.properties.kubernetes_namespace: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_ports"]) -> MetaOapg.properties.kubernetes_ports: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_public_ip"]) -> MetaOapg.properties.kubernetes_public_ip: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_state"]) -> MetaOapg.properties.kubernetes_state: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_type"]) -> MetaOapg.properties.kubernetes_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["local_cidr"]) -> MetaOapg.properties.local_cidr: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["local_networks"]) -> MetaOapg.properties.local_networks: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["memory_max"]) -> MetaOapg.properties.memory_max: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["memory_usage"]) -> MetaOapg.properties.memory_usage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_id"]) -> MetaOapg.properties.node_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_name"]) -> MetaOapg.properties.node_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_type"]) -> MetaOapg.properties.node_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["open_files"]) -> MetaOapg.properties.open_files: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["open_files_count"]) -> MetaOapg.properties.open_files_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["os"]) -> MetaOapg.properties.os: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pid"]) -> MetaOapg.properties.pid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pod_name"]) -> MetaOapg.properties.pod_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ppid"]) -> MetaOapg.properties.ppid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["private_ip"]) -> MetaOapg.properties.private_ip: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pseudo"]) -> MetaOapg.properties.pseudo: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["public_ip"]) -> MetaOapg.properties.public_ip: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resource_group"]) -> MetaOapg.properties.resource_group: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["threads"]) -> MetaOapg.properties.threads: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["uptime"]) -> MetaOapg.properties.uptime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["user_defined_tags"]) -> MetaOapg.properties.user_defined_tags: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["version"]) -> MetaOapg.properties.version: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["agent_running", "availability_zone", "cloud_provider", "cloud_region", "cmdline", "connection_count", "copy_of", "cpu_max", "cpu_usage", "docker_container_command", "docker_container_created", "docker_container_ips", "docker_container_name", "docker_container_network_mode", "docker_container_networks", "docker_container_ports", "docker_container_state", "docker_container_state_human", "docker_env", "docker_image_created_at", "docker_image_id", "docker_image_name", "docker_image_name_with_tag", "docker_image_size", "docker_image_tag", "docker_image_virtual_size", "docker_label", "host_name", "instance_id", "instance_type", "interface_ip_map", "interface_ips", "interface_names", "is_console_vm", "kernel_id", "kernel_version", "kubernetes_cluster_id", "kubernetes_cluster_name", "kubernetes_created", "kubernetes_ingress_ip", "kubernetes_ip", "kubernetes_is_in_host_network", "kubernetes_labels", "kubernetes_namespace", "kubernetes_ports", "kubernetes_public_ip", "kubernetes_state", "kubernetes_type", "local_cidr", "local_networks", "memory_max", "memory_usage", "node_id", "node_name", "node_type", "open_files", "open_files_count", "os", "pid", "pod_name", "ppid", "private_ip", "pseudo", "public_ip", "resource_group", "threads", "timestamp", "uptime", "user_defined_tags", "version", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["agent_running"]) -> typing.Union[MetaOapg.properties.agent_running, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["availability_zone"]) -> typing.Union[MetaOapg.properties.availability_zone, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cloud_provider"]) -> typing.Union[MetaOapg.properties.cloud_provider, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cloud_region"]) -> typing.Union[MetaOapg.properties.cloud_region, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cmdline"]) -> typing.Union[MetaOapg.properties.cmdline, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["connection_count"]) -> typing.Union[MetaOapg.properties.connection_count, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["copy_of"]) -> typing.Union[MetaOapg.properties.copy_of, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cpu_max"]) -> typing.Union[MetaOapg.properties.cpu_max, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cpu_usage"]) -> typing.Union[MetaOapg.properties.cpu_usage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_container_command"]) -> typing.Union[MetaOapg.properties.docker_container_command, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_container_created"]) -> typing.Union[MetaOapg.properties.docker_container_created, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_container_ips"]) -> typing.Union[MetaOapg.properties.docker_container_ips, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_container_name"]) -> typing.Union[MetaOapg.properties.docker_container_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_container_network_mode"]) -> typing.Union[MetaOapg.properties.docker_container_network_mode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_container_networks"]) -> typing.Union[MetaOapg.properties.docker_container_networks, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_container_ports"]) -> typing.Union[MetaOapg.properties.docker_container_ports, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_container_state"]) -> typing.Union[MetaOapg.properties.docker_container_state, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_container_state_human"]) -> typing.Union[MetaOapg.properties.docker_container_state_human, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_env"]) -> typing.Union[MetaOapg.properties.docker_env, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_image_created_at"]) -> typing.Union[MetaOapg.properties.docker_image_created_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_image_id"]) -> typing.Union[MetaOapg.properties.docker_image_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_image_name"]) -> typing.Union[MetaOapg.properties.docker_image_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_image_name_with_tag"]) -> typing.Union[MetaOapg.properties.docker_image_name_with_tag, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_image_size"]) -> typing.Union[MetaOapg.properties.docker_image_size, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_image_tag"]) -> typing.Union[MetaOapg.properties.docker_image_tag, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_image_virtual_size"]) -> typing.Union[MetaOapg.properties.docker_image_virtual_size, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["docker_label"]) -> typing.Union[MetaOapg.properties.docker_label, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["host_name"]) -> typing.Union[MetaOapg.properties.host_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["instance_id"]) -> typing.Union[MetaOapg.properties.instance_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["instance_type"]) -> typing.Union[MetaOapg.properties.instance_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["interface_ip_map"]) -> typing.Union[MetaOapg.properties.interface_ip_map, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["interface_ips"]) -> typing.Union[MetaOapg.properties.interface_ips, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["interface_names"]) -> typing.Union[MetaOapg.properties.interface_names, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_console_vm"]) -> typing.Union[MetaOapg.properties.is_console_vm, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kernel_id"]) -> typing.Union[MetaOapg.properties.kernel_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kernel_version"]) -> typing.Union[MetaOapg.properties.kernel_version, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_cluster_id"]) -> typing.Union[MetaOapg.properties.kubernetes_cluster_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_cluster_name"]) -> typing.Union[MetaOapg.properties.kubernetes_cluster_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_created"]) -> typing.Union[MetaOapg.properties.kubernetes_created, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_ingress_ip"]) -> typing.Union[MetaOapg.properties.kubernetes_ingress_ip, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_ip"]) -> typing.Union[MetaOapg.properties.kubernetes_ip, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_is_in_host_network"]) -> typing.Union[MetaOapg.properties.kubernetes_is_in_host_network, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_labels"]) -> typing.Union[MetaOapg.properties.kubernetes_labels, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_namespace"]) -> typing.Union[MetaOapg.properties.kubernetes_namespace, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_ports"]) -> typing.Union[MetaOapg.properties.kubernetes_ports, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_public_ip"]) -> typing.Union[MetaOapg.properties.kubernetes_public_ip, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_state"]) -> typing.Union[MetaOapg.properties.kubernetes_state, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_type"]) -> typing.Union[MetaOapg.properties.kubernetes_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["local_cidr"]) -> typing.Union[MetaOapg.properties.local_cidr, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["local_networks"]) -> typing.Union[MetaOapg.properties.local_networks, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["memory_max"]) -> typing.Union[MetaOapg.properties.memory_max, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["memory_usage"]) -> typing.Union[MetaOapg.properties.memory_usage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_id"]) -> typing.Union[MetaOapg.properties.node_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_name"]) -> typing.Union[MetaOapg.properties.node_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_type"]) -> typing.Union[MetaOapg.properties.node_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["open_files"]) -> typing.Union[MetaOapg.properties.open_files, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["open_files_count"]) -> typing.Union[MetaOapg.properties.open_files_count, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["os"]) -> typing.Union[MetaOapg.properties.os, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pid"]) -> typing.Union[MetaOapg.properties.pid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pod_name"]) -> typing.Union[MetaOapg.properties.pod_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ppid"]) -> typing.Union[MetaOapg.properties.ppid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["private_ip"]) -> typing.Union[MetaOapg.properties.private_ip, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pseudo"]) -> typing.Union[MetaOapg.properties.pseudo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["public_ip"]) -> typing.Union[MetaOapg.properties.public_ip, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resource_group"]) -> typing.Union[MetaOapg.properties.resource_group, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["threads"]) -> typing.Union[MetaOapg.properties.threads, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timestamp"]) -> typing.Union[MetaOapg.properties.timestamp, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["uptime"]) -> typing.Union[MetaOapg.properties.uptime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["user_defined_tags"]) -> typing.Union[MetaOapg.properties.user_defined_tags, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["version"]) -> typing.Union[MetaOapg.properties.version, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["agent_running", "availability_zone", "cloud_provider", "cloud_region", "cmdline", "connection_count", "copy_of", "cpu_max", "cpu_usage", "docker_container_command", "docker_container_created", "docker_container_ips", "docker_container_name", "docker_container_network_mode", "docker_container_networks", "docker_container_ports", "docker_container_state", "docker_container_state_human", "docker_env", "docker_image_created_at", "docker_image_id", "docker_image_name", "docker_image_name_with_tag", "docker_image_size", "docker_image_tag", "docker_image_virtual_size", "docker_label", "host_name", "instance_id", "instance_type", "interface_ip_map", "interface_ips", "interface_names", "is_console_vm", "kernel_id", "kernel_version", "kubernetes_cluster_id", "kubernetes_cluster_name", "kubernetes_created", "kubernetes_ingress_ip", "kubernetes_ip", "kubernetes_is_in_host_network", "kubernetes_labels", "kubernetes_namespace", "kubernetes_ports", "kubernetes_public_ip", "kubernetes_state", "kubernetes_type", "local_cidr", "local_networks", "memory_max", "memory_usage", "node_id", "node_name", "node_type", "open_files", "open_files_count", "os", "pid", "pod_name", "ppid", "private_ip", "pseudo", "public_ip", "resource_group", "threads", "timestamp", "uptime", "user_defined_tags", "version", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        agent_running: typing.Union[MetaOapg.properties.agent_running, bool, schemas.Unset] = schemas.unset,
        availability_zone: typing.Union[MetaOapg.properties.availability_zone, str, schemas.Unset] = schemas.unset,
        cloud_provider: typing.Union[MetaOapg.properties.cloud_provider, str, schemas.Unset] = schemas.unset,
        cloud_region: typing.Union[MetaOapg.properties.cloud_region, str, schemas.Unset] = schemas.unset,
        cmdline: typing.Union[MetaOapg.properties.cmdline, str, schemas.Unset] = schemas.unset,
        connection_count: typing.Union[MetaOapg.properties.connection_count, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        copy_of: typing.Union[MetaOapg.properties.copy_of, str, schemas.Unset] = schemas.unset,
        cpu_max: typing.Union[MetaOapg.properties.cpu_max, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        cpu_usage: typing.Union[MetaOapg.properties.cpu_usage, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        docker_container_command: typing.Union[MetaOapg.properties.docker_container_command, str, schemas.Unset] = schemas.unset,
        docker_container_created: typing.Union[MetaOapg.properties.docker_container_created, str, schemas.Unset] = schemas.unset,
        docker_container_ips: typing.Union[MetaOapg.properties.docker_container_ips, list, tuple, schemas.Unset] = schemas.unset,
        docker_container_name: typing.Union[MetaOapg.properties.docker_container_name, str, schemas.Unset] = schemas.unset,
        docker_container_network_mode: typing.Union[MetaOapg.properties.docker_container_network_mode, str, schemas.Unset] = schemas.unset,
        docker_container_networks: typing.Union[MetaOapg.properties.docker_container_networks, str, schemas.Unset] = schemas.unset,
        docker_container_ports: typing.Union[MetaOapg.properties.docker_container_ports, str, schemas.Unset] = schemas.unset,
        docker_container_state: typing.Union[MetaOapg.properties.docker_container_state, str, schemas.Unset] = schemas.unset,
        docker_container_state_human: typing.Union[MetaOapg.properties.docker_container_state_human, str, schemas.Unset] = schemas.unset,
        docker_env: typing.Union[MetaOapg.properties.docker_env, str, schemas.Unset] = schemas.unset,
        docker_image_created_at: typing.Union[MetaOapg.properties.docker_image_created_at, str, schemas.Unset] = schemas.unset,
        docker_image_id: typing.Union[MetaOapg.properties.docker_image_id, str, schemas.Unset] = schemas.unset,
        docker_image_name: typing.Union[MetaOapg.properties.docker_image_name, str, schemas.Unset] = schemas.unset,
        docker_image_name_with_tag: typing.Union[MetaOapg.properties.docker_image_name_with_tag, str, schemas.Unset] = schemas.unset,
        docker_image_size: typing.Union[MetaOapg.properties.docker_image_size, str, schemas.Unset] = schemas.unset,
        docker_image_tag: typing.Union[MetaOapg.properties.docker_image_tag, str, schemas.Unset] = schemas.unset,
        docker_image_virtual_size: typing.Union[MetaOapg.properties.docker_image_virtual_size, str, schemas.Unset] = schemas.unset,
        docker_label: typing.Union[MetaOapg.properties.docker_label, str, schemas.Unset] = schemas.unset,
        host_name: typing.Union[MetaOapg.properties.host_name, str, schemas.Unset] = schemas.unset,
        instance_id: typing.Union[MetaOapg.properties.instance_id, str, schemas.Unset] = schemas.unset,
        instance_type: typing.Union[MetaOapg.properties.instance_type, str, schemas.Unset] = schemas.unset,
        interface_ip_map: typing.Union[MetaOapg.properties.interface_ip_map, str, schemas.Unset] = schemas.unset,
        interface_ips: typing.Union[MetaOapg.properties.interface_ips, list, tuple, schemas.Unset] = schemas.unset,
        interface_names: typing.Union[MetaOapg.properties.interface_names, list, tuple, schemas.Unset] = schemas.unset,
        is_console_vm: typing.Union[MetaOapg.properties.is_console_vm, bool, schemas.Unset] = schemas.unset,
        kernel_id: typing.Union[MetaOapg.properties.kernel_id, str, schemas.Unset] = schemas.unset,
        kernel_version: typing.Union[MetaOapg.properties.kernel_version, str, schemas.Unset] = schemas.unset,
        kubernetes_cluster_id: typing.Union[MetaOapg.properties.kubernetes_cluster_id, str, schemas.Unset] = schemas.unset,
        kubernetes_cluster_name: typing.Union[MetaOapg.properties.kubernetes_cluster_name, str, schemas.Unset] = schemas.unset,
        kubernetes_created: typing.Union[MetaOapg.properties.kubernetes_created, str, schemas.Unset] = schemas.unset,
        kubernetes_ingress_ip: typing.Union[MetaOapg.properties.kubernetes_ingress_ip, list, tuple, schemas.Unset] = schemas.unset,
        kubernetes_ip: typing.Union[MetaOapg.properties.kubernetes_ip, str, schemas.Unset] = schemas.unset,
        kubernetes_is_in_host_network: typing.Union[MetaOapg.properties.kubernetes_is_in_host_network, bool, schemas.Unset] = schemas.unset,
        kubernetes_labels: typing.Union[MetaOapg.properties.kubernetes_labels, str, schemas.Unset] = schemas.unset,
        kubernetes_namespace: typing.Union[MetaOapg.properties.kubernetes_namespace, str, schemas.Unset] = schemas.unset,
        kubernetes_ports: typing.Union[MetaOapg.properties.kubernetes_ports, list, tuple, schemas.Unset] = schemas.unset,
        kubernetes_public_ip: typing.Union[MetaOapg.properties.kubernetes_public_ip, str, schemas.Unset] = schemas.unset,
        kubernetes_state: typing.Union[MetaOapg.properties.kubernetes_state, str, schemas.Unset] = schemas.unset,
        kubernetes_type: typing.Union[MetaOapg.properties.kubernetes_type, str, schemas.Unset] = schemas.unset,
        local_cidr: typing.Union[MetaOapg.properties.local_cidr, list, tuple, schemas.Unset] = schemas.unset,
        local_networks: typing.Union[MetaOapg.properties.local_networks, list, tuple, schemas.Unset] = schemas.unset,
        memory_max: typing.Union[MetaOapg.properties.memory_max, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        memory_usage: typing.Union[MetaOapg.properties.memory_usage, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        node_id: typing.Union[MetaOapg.properties.node_id, str, schemas.Unset] = schemas.unset,
        node_name: typing.Union[MetaOapg.properties.node_name, str, schemas.Unset] = schemas.unset,
        node_type: typing.Union[MetaOapg.properties.node_type, str, schemas.Unset] = schemas.unset,
        open_files: typing.Union[MetaOapg.properties.open_files, list, tuple, schemas.Unset] = schemas.unset,
        open_files_count: typing.Union[MetaOapg.properties.open_files_count, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        os: typing.Union[MetaOapg.properties.os, str, schemas.Unset] = schemas.unset,
        pid: typing.Union[MetaOapg.properties.pid, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        pod_name: typing.Union[MetaOapg.properties.pod_name, str, schemas.Unset] = schemas.unset,
        ppid: typing.Union[MetaOapg.properties.ppid, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        private_ip: typing.Union[MetaOapg.properties.private_ip, list, tuple, schemas.Unset] = schemas.unset,
        pseudo: typing.Union[MetaOapg.properties.pseudo, bool, schemas.Unset] = schemas.unset,
        public_ip: typing.Union[MetaOapg.properties.public_ip, list, tuple, schemas.Unset] = schemas.unset,
        resource_group: typing.Union[MetaOapg.properties.resource_group, str, schemas.Unset] = schemas.unset,
        threads: typing.Union[MetaOapg.properties.threads, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        timestamp: typing.Union[MetaOapg.properties.timestamp, str, schemas.Unset] = schemas.unset,
        uptime: typing.Union[MetaOapg.properties.uptime, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        user_defined_tags: typing.Union[MetaOapg.properties.user_defined_tags, list, tuple, schemas.Unset] = schemas.unset,
        version: typing.Union[MetaOapg.properties.version, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ReportMetadata':
        return super().__new__(
            cls,
            *_args,
            agent_running=agent_running,
            availability_zone=availability_zone,
            cloud_provider=cloud_provider,
            cloud_region=cloud_region,
            cmdline=cmdline,
            connection_count=connection_count,
            copy_of=copy_of,
            cpu_max=cpu_max,
            cpu_usage=cpu_usage,
            docker_container_command=docker_container_command,
            docker_container_created=docker_container_created,
            docker_container_ips=docker_container_ips,
            docker_container_name=docker_container_name,
            docker_container_network_mode=docker_container_network_mode,
            docker_container_networks=docker_container_networks,
            docker_container_ports=docker_container_ports,
            docker_container_state=docker_container_state,
            docker_container_state_human=docker_container_state_human,
            docker_env=docker_env,
            docker_image_created_at=docker_image_created_at,
            docker_image_id=docker_image_id,
            docker_image_name=docker_image_name,
            docker_image_name_with_tag=docker_image_name_with_tag,
            docker_image_size=docker_image_size,
            docker_image_tag=docker_image_tag,
            docker_image_virtual_size=docker_image_virtual_size,
            docker_label=docker_label,
            host_name=host_name,
            instance_id=instance_id,
            instance_type=instance_type,
            interface_ip_map=interface_ip_map,
            interface_ips=interface_ips,
            interface_names=interface_names,
            is_console_vm=is_console_vm,
            kernel_id=kernel_id,
            kernel_version=kernel_version,
            kubernetes_cluster_id=kubernetes_cluster_id,
            kubernetes_cluster_name=kubernetes_cluster_name,
            kubernetes_created=kubernetes_created,
            kubernetes_ingress_ip=kubernetes_ingress_ip,
            kubernetes_ip=kubernetes_ip,
            kubernetes_is_in_host_network=kubernetes_is_in_host_network,
            kubernetes_labels=kubernetes_labels,
            kubernetes_namespace=kubernetes_namespace,
            kubernetes_ports=kubernetes_ports,
            kubernetes_public_ip=kubernetes_public_ip,
            kubernetes_state=kubernetes_state,
            kubernetes_type=kubernetes_type,
            local_cidr=local_cidr,
            local_networks=local_networks,
            memory_max=memory_max,
            memory_usage=memory_usage,
            node_id=node_id,
            node_name=node_name,
            node_type=node_type,
            open_files=open_files,
            open_files_count=open_files_count,
            os=os,
            pid=pid,
            pod_name=pod_name,
            ppid=ppid,
            private_ip=private_ip,
            pseudo=pseudo,
            public_ip=public_ip,
            resource_group=resource_group,
            threads=threads,
            timestamp=timestamp,
            uptime=uptime,
            user_defined_tags=user_defined_tags,
            version=version,
            _configuration=_configuration,
            **kwargs,
        )
