# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class ReportersFieldsFilters(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "compare_filter",
            "order_filter",
            "contains_filter",
            "match_filter",
        }
        
        class properties:
            
            
            class compare_filter(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ReportersCompareFilter']:
                        return ReportersCompareFilter
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'compare_filter':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def contains_filter() -> typing.Type['ReportersContainsFilter']:
                return ReportersContainsFilter
        
            @staticmethod
            def match_filter() -> typing.Type['ReportersMatchFilter']:
                return ReportersMatchFilter
        
            @staticmethod
            def order_filter() -> typing.Type['ReportersOrderFilter']:
                return ReportersOrderFilter
        
            @staticmethod
            def not_contains_filter() -> typing.Type['ReportersContainsFilter']:
                return ReportersContainsFilter
            __annotations__ = {
                "compare_filter": compare_filter,
                "contains_filter": contains_filter,
                "match_filter": match_filter,
                "order_filter": order_filter,
                "not_contains_filter": not_contains_filter,
            }
    
    compare_filter: MetaOapg.properties.compare_filter
    order_filter: 'ReportersOrderFilter'
    contains_filter: 'ReportersContainsFilter'
    match_filter: 'ReportersMatchFilter'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["compare_filter"]) -> MetaOapg.properties.compare_filter: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contains_filter"]) -> 'ReportersContainsFilter': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["match_filter"]) -> 'ReportersMatchFilter': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["order_filter"]) -> 'ReportersOrderFilter': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["not_contains_filter"]) -> 'ReportersContainsFilter': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["compare_filter", "contains_filter", "match_filter", "order_filter", "not_contains_filter", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["compare_filter"]) -> MetaOapg.properties.compare_filter: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contains_filter"]) -> 'ReportersContainsFilter': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["match_filter"]) -> 'ReportersMatchFilter': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["order_filter"]) -> 'ReportersOrderFilter': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["not_contains_filter"]) -> typing.Union['ReportersContainsFilter', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["compare_filter", "contains_filter", "match_filter", "order_filter", "not_contains_filter", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        compare_filter: typing.Union[MetaOapg.properties.compare_filter, list, tuple, None, ],
        order_filter: 'ReportersOrderFilter',
        contains_filter: 'ReportersContainsFilter',
        match_filter: 'ReportersMatchFilter',
        not_contains_filter: typing.Union['ReportersContainsFilter', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ReportersFieldsFilters':
        return super().__new__(
            cls,
            *_args,
            compare_filter=compare_filter,
            order_filter=order_filter,
            contains_filter=contains_filter,
            match_filter=match_filter,
            not_contains_filter=not_contains_filter,
            _configuration=_configuration,
            **kwargs,
        )

from threatmapper.model.reporters_compare_filter import ReportersCompareFilter
from threatmapper.model.reporters_contains_filter import ReportersContainsFilter
from threatmapper.model.reporters_match_filter import ReportersMatchFilter
from threatmapper.model.reporters_order_filter import ReportersOrderFilter
