# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class SearchNodeCountResp(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "container",
            "pod",
            "host",
            "namespace",
            "cloud_provider",
            "kubernetes_cluster",
            "container_image",
        }
        
        class properties:
            cloud_provider = schemas.IntSchema
            container = schemas.IntSchema
            container_image = schemas.IntSchema
            host = schemas.IntSchema
            kubernetes_cluster = schemas.IntSchema
            namespace = schemas.IntSchema
            pod = schemas.IntSchema
            __annotations__ = {
                "cloud_provider": cloud_provider,
                "container": container,
                "container_image": container_image,
                "host": host,
                "kubernetes_cluster": kubernetes_cluster,
                "namespace": namespace,
                "pod": pod,
            }
    
    container: MetaOapg.properties.container
    pod: MetaOapg.properties.pod
    host: MetaOapg.properties.host
    namespace: MetaOapg.properties.namespace
    cloud_provider: MetaOapg.properties.cloud_provider
    kubernetes_cluster: MetaOapg.properties.kubernetes_cluster
    container_image: MetaOapg.properties.container_image
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cloud_provider"]) -> MetaOapg.properties.cloud_provider: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["container"]) -> MetaOapg.properties.container: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["container_image"]) -> MetaOapg.properties.container_image: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["host"]) -> MetaOapg.properties.host: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kubernetes_cluster"]) -> MetaOapg.properties.kubernetes_cluster: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["namespace"]) -> MetaOapg.properties.namespace: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pod"]) -> MetaOapg.properties.pod: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cloud_provider", "container", "container_image", "host", "kubernetes_cluster", "namespace", "pod", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cloud_provider"]) -> MetaOapg.properties.cloud_provider: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["container"]) -> MetaOapg.properties.container: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["container_image"]) -> MetaOapg.properties.container_image: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["host"]) -> MetaOapg.properties.host: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kubernetes_cluster"]) -> MetaOapg.properties.kubernetes_cluster: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["namespace"]) -> MetaOapg.properties.namespace: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pod"]) -> MetaOapg.properties.pod: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cloud_provider", "container", "container_image", "host", "kubernetes_cluster", "namespace", "pod", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        container: typing.Union[MetaOapg.properties.container, decimal.Decimal, int, ],
        pod: typing.Union[MetaOapg.properties.pod, decimal.Decimal, int, ],
        host: typing.Union[MetaOapg.properties.host, decimal.Decimal, int, ],
        namespace: typing.Union[MetaOapg.properties.namespace, decimal.Decimal, int, ],
        cloud_provider: typing.Union[MetaOapg.properties.cloud_provider, decimal.Decimal, int, ],
        kubernetes_cluster: typing.Union[MetaOapg.properties.kubernetes_cluster, decimal.Decimal, int, ],
        container_image: typing.Union[MetaOapg.properties.container_image, decimal.Decimal, int, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SearchNodeCountResp':
        return super().__new__(
            cls,
            *_args,
            container=container,
            pod=pod,
            host=host,
            namespace=namespace,
            cloud_provider=cloud_provider,
            kubernetes_cluster=kubernetes_cluster,
            container_image=container_image,
            _configuration=_configuration,
            **kwargs,
        )
