# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from threatmapper import schemas  # noqa: F401


class UtilsReportFilters(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "node_type",
            "scan_type",
        }
        
        class properties:
            
            
            class node_type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def HOST(cls):
                    return cls("host")
                
                @schemas.classproperty
                def CONTAINER(cls):
                    return cls("container")
                
                @schemas.classproperty
                def CONTAINER_IMAGE(cls):
                    return cls("container_image")
                
                @schemas.classproperty
                def LINUX(cls):
                    return cls("linux")
                
                @schemas.classproperty
                def CLUSTER(cls):
                    return cls("cluster")
                
                @schemas.classproperty
                def AWS(cls):
                    return cls("aws")
                
                @schemas.classproperty
                def GCP(cls):
                    return cls("gcp")
                
                @schemas.classproperty
                def AZURE(cls):
                    return cls("azure")
            
            
            class scan_type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def VULNERABILITY(cls):
                    return cls("vulnerability")
                
                @schemas.classproperty
                def SECRET(cls):
                    return cls("secret")
                
                @schemas.classproperty
                def MALWARE(cls):
                    return cls("malware")
                
                @schemas.classproperty
                def COMPLIANCE(cls):
                    return cls("compliance")
                
                @schemas.classproperty
                def CLOUD_COMPLIANCE(cls):
                    return cls("cloud_compliance")
        
            @staticmethod
            def advanced_report_filters() -> typing.Type['UtilsAdvancedReportFilters']:
                return UtilsAdvancedReportFilters
            include_dead_nodes = schemas.BoolSchema
            scan_id = schemas.StrSchema
            
            
            class severity_or_check_type(
                schemas.EnumBase,
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                    }
                    items = schemas.StrSchema
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'severity_or_check_type':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "node_type": node_type,
                "scan_type": scan_type,
                "advanced_report_filters": advanced_report_filters,
                "include_dead_nodes": include_dead_nodes,
                "scan_id": scan_id,
                "severity_or_check_type": severity_or_check_type,
            }
    
    node_type: MetaOapg.properties.node_type
    scan_type: MetaOapg.properties.scan_type
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["node_type"]) -> MetaOapg.properties.node_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scan_type"]) -> MetaOapg.properties.scan_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["advanced_report_filters"]) -> 'UtilsAdvancedReportFilters': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["include_dead_nodes"]) -> MetaOapg.properties.include_dead_nodes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scan_id"]) -> MetaOapg.properties.scan_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["severity_or_check_type"]) -> MetaOapg.properties.severity_or_check_type: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["node_type", "scan_type", "advanced_report_filters", "include_dead_nodes", "scan_id", "severity_or_check_type", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["node_type"]) -> MetaOapg.properties.node_type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scan_type"]) -> MetaOapg.properties.scan_type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["advanced_report_filters"]) -> typing.Union['UtilsAdvancedReportFilters', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["include_dead_nodes"]) -> typing.Union[MetaOapg.properties.include_dead_nodes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scan_id"]) -> typing.Union[MetaOapg.properties.scan_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["severity_or_check_type"]) -> typing.Union[MetaOapg.properties.severity_or_check_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["node_type", "scan_type", "advanced_report_filters", "include_dead_nodes", "scan_id", "severity_or_check_type", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        node_type: typing.Union[MetaOapg.properties.node_type, str, ],
        scan_type: typing.Union[MetaOapg.properties.scan_type, str, ],
        advanced_report_filters: typing.Union['UtilsAdvancedReportFilters', schemas.Unset] = schemas.unset,
        include_dead_nodes: typing.Union[MetaOapg.properties.include_dead_nodes, bool, schemas.Unset] = schemas.unset,
        scan_id: typing.Union[MetaOapg.properties.scan_id, str, schemas.Unset] = schemas.unset,
        severity_or_check_type: typing.Union[MetaOapg.properties.severity_or_check_type, list, tuple, None, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UtilsReportFilters':
        return super().__new__(
            cls,
            *_args,
            node_type=node_type,
            scan_type=scan_type,
            advanced_report_filters=advanced_report_filters,
            include_dead_nodes=include_dead_nodes,
            scan_id=scan_id,
            severity_or_check_type=severity_or_check_type,
            _configuration=_configuration,
            **kwargs,
        )

from threatmapper.model.utils_advanced_report_filters import UtilsAdvancedReportFilters
