# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import threatmapper
from threatmapper.paths.deepfence_user_reset_password_verify import post  # noqa: E501
from threatmapper import configuration, schemas, api_client

from .. import ApiTestMixin


class TestDeepfenceUserResetPasswordVerify(ApiTestMixin, unittest.TestCase):
    """
    DeepfenceUserResetPasswordVerify unit test stubs
        Verify and Reset Password  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 204
    response_body = ''


if __name__ == '__main__':
    unittest.main()
