# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from threatmapper.paths.deepfence_scan_results_count_compliance.post import CountResultsComplianceScan
from threatmapper.paths.deepfence_ingest_compliance.post import IngestCompliances
from threatmapper.paths.deepfence_scan_list_compliance.post import ListComplianceScan
from threatmapper.paths.deepfence_scan_results_compliance.post import ResultsComplianceScan
from threatmapper.paths.deepfence_scan_start_compliance.post import StartComplianceScan
from threatmapper.paths.deepfence_scan_status_compliance.post import StatusComplianceScan
from threatmapper.paths.deepfence_scan_stop_compliance.post import StopComplianceScan


class ComplianceApi(
    CountResultsComplianceScan,
    IngestCompliances,
    ListComplianceScan,
    ResultsComplianceScan,
    StartComplianceScan,
    StatusComplianceScan,
    StopComplianceScan,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
