# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from threatmapper.paths.deepfence_diagnosis_notification.get import DiagnosticNotification
from threatmapper.paths.deepfence_diagnosis_agent_logs.post import GenerateAgentDiagnosticLogs
from threatmapper.paths.deepfence_diagnosis_console_logs.post import GenerateConsoleDiagnosticLogs
from threatmapper.paths.deepfence_diagnosis_diagnostic_logs.get import GetDiagnosticLogs
from threatmapper.paths.deepfence_diagnosis_agent_logs_status_node_id.put import UpdateAgentDiagnosticLogsStatus


class DiagnosisApi(
    DiagnosticNotification,
    GenerateAgentDiagnosticLogs,
    GenerateConsoleDiagnosticLogs,
    GetDiagnosticLogs,
    UpdateAgentDiagnosticLogsStatus,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
