# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from threatmapper.paths.deepfence_lookup_cloud_resources.post import GetCloudResources
from threatmapper.paths.deepfence_lookup_containerimages.post import GetContainerImages
from threatmapper.paths.deepfence_lookup_containers.post import GetContainers
from threatmapper.paths.deepfence_lookup_hosts.post import GetHosts
from threatmapper.paths.deepfence_lookup_kubernetesclusters.post import GetKubernetesClusters
from threatmapper.paths.deepfence_lookup_pods.post import GetPods
from threatmapper.paths.deepfence_lookup_processes.post import GetProcesses
from threatmapper.paths.deepfence_lookup_registryaccount.post import GetRegistryAccount


class LookupApi(
    GetCloudResources,
    GetContainerImages,
    GetContainers,
    GetHosts,
    GetKubernetesClusters,
    GetPods,
    GetProcesses,
    GetRegistryAccount,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
