# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from threatmapper.paths.deepfence_registryaccount.post import AddRegistry
from threatmapper.paths.deepfence_registryaccount_gcr.post import AddRegistryGcr
from threatmapper.paths.deepfence_registryaccount_count_stubs.post import CountImageStubs
from threatmapper.paths.deepfence_registryaccount_count_images.post import CountImages
from threatmapper.paths.deepfence_registryaccount_registry_id.delete import DeleteRegistry
from threatmapper.paths.deepfence_registryaccount_registry_id_summary.get import GetRegistrySummary
from threatmapper.paths.deepfence_registryaccount_summary.get import GetSummaryAll
from threatmapper.paths.deepfence_registryaccount_registry_type_summary_by_type.get import GetSummaryByType
from threatmapper.paths.deepfence_registryaccount_stubs.post import ListImageStubs
from threatmapper.paths.deepfence_registryaccount_images.post import ListImages
from threatmapper.paths.deepfence_registryaccount.get import ListRegistry
from threatmapper.paths.deepfence_registryaccount_registry_id.put import UpdateRegistry


class RegistryApi(
    AddRegistry,
    AddRegistryGcr,
    CountImageStubs,
    CountImages,
    DeleteRegistry,
    GetRegistrySummary,
    GetSummaryAll,
    GetSummaryByType,
    ListImageStubs,
    ListImages,
    ListRegistry,
    UpdateRegistry,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
