# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from threatmapper.paths.deepfence_scan_results_count_secret.post import CountResultsSecretScan
from threatmapper.paths.deepfence_scan_results_count_group_secret.get import GroupResultsSecrets
from threatmapper.paths.deepfence_ingest_secret_scan_logs.post import IngestSecretScanStatus
from threatmapper.paths.deepfence_ingest_secrets.post import IngestSecrets
from threatmapper.paths.deepfence_scan_list_secret.post import ListSecretScan
from threatmapper.paths.deepfence_scan_results_secret_rules.post import ResultsRulesSecretScan
from threatmapper.paths.deepfence_scan_results_secret.post import ResultsSecretScan
from threatmapper.paths.deepfence_scan_start_secret.post import StartSecretScan
from threatmapper.paths.deepfence_scan_status_secret.post import StatusSecretScan
from threatmapper.paths.deepfence_scan_stop_secret.post import StopSecretScan


class SecretScanApi(
    CountResultsSecretScan,
    GroupResultsSecrets,
    IngestSecretScanStatus,
    IngestSecrets,
    ListSecretScan,
    ResultsRulesSecretScan,
    ResultsSecretScan,
    StartSecretScan,
    StatusSecretScan,
    StopSecretScan,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
