# coding: utf-8

"""
    Deepfence ThreatMapper

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: community@deepfence.io
    Generated by: https://openapi-generator.tech
"""

from threatmapper.paths.deepfence_user.delete import DeleteCurrentUser
from threatmapper.paths.deepfence_users_id.delete import DeleteUser
from threatmapper.paths.deepfence_api_token.get import GetApiTokens
from threatmapper.paths.deepfence_user.get import GetCurrentUser
from threatmapper.paths.deepfence_users_id.get import GetUser
from threatmapper.paths.deepfence_users.get import GetUsers
from threatmapper.paths.deepfence_user_invite.post import InviteUser
from threatmapper.paths.deepfence_user_invite_register.post import RegisterInvitedUser
from threatmapper.paths.deepfence_user_register.post import RegisterUser
from threatmapper.paths.deepfence_api_token_reset.post import ResetApiTokens
from threatmapper.paths.deepfence_user_reset_password_request.post import ResetPasswordRequest
from threatmapper.paths.deepfence_user.put import UpdateCurrentUser
from threatmapper.paths.deepfence_user_password.put import UpdatePassword
from threatmapper.paths.deepfence_users_id.put import UpdateUser
from threatmapper.paths.deepfence_user_reset_password_verify.post import VerifyResetPasswordRequest


class UserApi(
    DeleteCurrentUser,
    DeleteUser,
    GetApiTokens,
    GetCurrentUser,
    GetUser,
    GetUsers,
    InviteUser,
    RegisterInvitedUser,
    RegisterUser,
    ResetApiTokens,
    ResetPasswordRequest,
    UpdateCurrentUser,
    UpdatePassword,
    UpdateUser,
    VerifyResetPasswordRequest,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
